// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("account")]
    [Index(nameof(CreationCssSiteId), Name = "ind_acc_creation_css_site")]
    [Index(nameof(Status), Name = "ind_account_status")]
    public partial class Account
    {
        [Key]
        [Column("id", TypeName = "numeric(18, 0)")]
        public decimal Id { get; set; }
        [Column("creation_system_id")]
        public byte? CreationSystemId { get; set; }
        [Column("creation_css_site_id")]
        public short? CreationCssSiteId { get; set; }
        [Column("account_name")]
        [StringLength(40)]
        public string AccountName { get; set; }
        [Column("status")]
        [StringLength(10)]
        public string Status { get; set; }
        [Column("creation_datetime", TypeName = "datetime")]
        public DateTime? CreationDatetime { get; set; }
        [Column("expiry_datetime", TypeName = "datetime")]
        public DateTime? ExpiryDatetime { get; set; }
        [Column("suspend_start_datetime", TypeName = "datetime")]
        public DateTime? SuspendStartDatetime { get; set; }
        [Column("suspend_end_datetime", TypeName = "datetime")]
        public DateTime? SuspendEndDatetime { get; set; }
        [Column("last_modified_datetime", TypeName = "datetime")]
        public DateTime? LastModifiedDatetime { get; set; }
        [Column("cash_flag")]
        [StringLength(1)]
        public string CashFlag { get; set; }
    }
}