// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("account_balance")]
    public partial class AccountBalance
    {
        [Key]
        [Column("account_id", TypeName = "numeric(18, 0)")]
        public decimal AccountId { get; set; }
        [Key]
        [Column("tracking_type_id")]
        public byte TrackingTypeId { get; set; }
        [Column("balance", TypeName = "numeric(18, 0)")]
        public decimal Balance { get; set; }
        [Column("available_balance", TypeName = "numeric(18, 0)")]
        public decimal? AvailableBalance { get; set; }
    }
}