// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("account_transaction_summary")]
    [Index(nameof(CssSiteId), nameof(StartDatetime), Name = "IXSUM_account_transaction_VenueDailyCardSummaryCGS_Data")]
    [Index(nameof(SummaryLevel), nameof(CssSiteId), nameof(StartDatetime), Name = "ind_account_transaction_summary_recalc")]
    [Index(nameof(StartDatetime), nameof(SummaryLevel), Name = "ind_ats_dt_sl")]
    [Index(nameof(SummaryLevel), nameof(StartDatetime), Name = "ind_ats_sl_dt")]
    [Index(nameof(CssSiteId), nameof(TransactionId), Name = "ind_site_trans_id")]
    [Index(nameof(Status), Name = "ind_status")]
    public partial class AccountTransactionSummary
    {
        [Key]
        [Column("account_id", TypeName = "numeric(18, 0)")]
        public decimal AccountId { get; set; }
        [Key]
        [Column("card_id")]
        public int CardId { get; set; }
        [Key]
        [Column("summary_level")]
        public short SummaryLevel { get; set; }
        [Key]
        [Column("start_datetime", TypeName = "datetime")]
        public DateTime StartDatetime { get; set; }
        [Key]
        [Column("transaction_type_id")]
        public byte TransactionTypeId { get; set; }
        [Key]
        [Column("tracking_type_id")]
        public byte TrackingTypeId { get; set; }
        [Key]
        [Column("css_site_id")]
        public short CssSiteId { get; set; }
        [Column("logged_datetime", TypeName = "datetime")]
        public DateTime LoggedDatetime { get; set; }
        [Column("record_count")]
        public int? RecordCount { get; set; }
        [Column("amount", TypeName = "numeric(18, 0)")]
        public decimal? Amount { get; set; }
        [Column("new_balance", TypeName = "numeric(18, 0)")]
        public decimal? NewBalance { get; set; }
        [Column("status")]
        [StringLength(10)]
        public string Status { get; set; }
        [Column("system_id")]
        public byte? SystemId { get; set; }
        [Column("description")]
        [StringLength(255)]
        public string Description { get; set; }
        [Column("transaction_id")]
        public int? TransactionId { get; set; }
        [Column("exchange_rate")]
        public double? ExchangeRate { get; set; }
        [Column("object_id_1", TypeName = "numeric(18, 0)")]
        public decimal? ObjectId1 { get; set; }
        [Column("object_id_2", TypeName = "numeric(18, 0)")]
        public decimal? ObjectId2 { get; set; }
    }
}