// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("account_summary")]
    [Index(nameof(PeriodStartDatetime), nameof(Amount), Name = "ind_start_datetime_amount")]
    public partial class AccountSummary
    {
        [Key]
        [Column("account_id", TypeName = "numeric(18, 0)")]
        public decimal AccountId { get; set; }
        [Key]
        [Column("patron_id", TypeName = "numeric(18, 0)")]
        public decimal PatronId { get; set; }
        [Key]
        [Column("tracking_type_id")]
        public byte TrackingTypeId { get; set; }
        [Key]
        [Column("period")]
        public short Period { get; set; }
        [Column("period_start_datetime", TypeName = "datetime")]
        public DateTime? PeriodStartDatetime { get; set; }
        [Column("amount", TypeName = "numeric(18, 0)")]
        public decimal Amount { get; set; }
    }
}