// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("account_transaction_type")]
    public partial class AccountTransactionType
    {
        [Key]
        [Column("id")]
        public byte Id { get; set; }
        [Column("description")]
        [StringLength(30)]
        public string Description { get; set; }
        [Column("account_permission_type_id")]
        public short? AccountPermissionTypeId { get; set; }
        [Column("sign")]
        [StringLength(1)]
        public string Sign { get; set; }
        [Column("cash_flag")]
        [StringLength(1)]
        public string CashFlag { get; set; }
    }
}