// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("ad_make")]
    public partial class AdMake
    {
        [Key]
        [Column("cougar_id")]
        public int CougarId { get; set; }
        [Key]
        [Column("activdata_id")]
        public int ActivdataId { get; set; }
        [Required]
        [Column("make")]
        [StringLength(30)]
        public string Make { get; set; }
    }
}