// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("alh_session_id")]
    public partial class AlhSessionId
    {
        [Key]
        [Column("processed_datetime", TypeName = "datetime")]
        public DateTime ProcessedDatetime { get; set; }
        [Key]
        [Column("session_id")]
        [StringLength(22)]
        public string SessionId { get; set; }
    }
}