// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("atc_files_in")]
    public partial class AtcFilesIn
    {
        [Key]
        [Column("file_datetime", TypeName = "datetime")]
        public DateTime FileDatetime { get; set; }
        [Key]
        [Column("increment")]
        public int Increment { get; set; }
        [Required]
        [Column("success")]
        [StringLength(1)]
        public string Success { get; set; }
    }
}