// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("audit")]
    [Index(nameof(AuditDatetime), nameof(SiteId), Name = "IX_auditdatetime_siteid")]
    [Index(nameof(AuditDatetime), Name = "ind_audit_datetime")]
    [Index(nameof(AuditDatetime), nameof(AuditOperationId), Name = "ind_audit_dt_op_id")]
    [Index(nameof(LoggedDatetime), nameof(EgmSerialNumber), Name = "ind_audit_egm_date")]
    [Index(nameof(LoggedDatetime), Name = "ind_audit_logged")]
    [Index(nameof(AuditOperationId), nameof(EgmSerialNumber), Name = "ind_audit_operation_id")]
    [Index(nameof(AuditOperationId), nameof(AuditDatetime), Name = "ind_audit_opid_auddt")]
    [Index(nameof(UserId), nameof(LoggedDatetime), Name = "ind_audit_user_date")]
    public partial class Audit
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("id", TypeName = "numeric(18, 0)")]
        public decimal Id { get; set; }
        [Column("user_id")]
        [StringLength(10)]
        public string UserId { get; set; }
        [Column("audit_operation_id")]
        public short AuditOperationId { get; set; }
        [Column("logged_datetime", TypeName = "datetime")]
        public DateTime LoggedDatetime { get; set; }
        [Column("audit_datetime", TypeName = "datetime")]
        public DateTime? AuditDatetime { get; set; }
        [Column("egm_serial_number")]
        public int? EgmSerialNumber { get; set; }
        [Column("player_id")]
        public int? PlayerId { get; set; }
        [Column("amount")]
        public int? Amount { get; set; }
        [Column("comment_string")]
        [StringLength(50)]
        public string CommentString { get; set; }
        [Column("amount_2")]
        public int? Amount2 { get; set; }
        [Column("comment_string_1")]
        [StringLength(50)]
        public string CommentString1 { get; set; }
        [Column("comment_string_2")]
        [StringLength(50)]
        public string CommentString2 { get; set; }
        [Column("comment_string_3")]
        [StringLength(50)]
        public string CommentString3 { get; set; }
        [Column("comment_string_4")]
        [StringLength(50)]
        public string CommentString4 { get; set; }
    }
}