// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("barrel_draw_prize")]
    public partial class BarrelDrawPrize
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("promotion_id", TypeName = "numeric(18, 0)")]
        public decimal PromotionId { get; set; }
        [Key]
        [Column("draw_number")]
        public short DrawNumber { get; set; }
        [Required]
        [Column("prize_description")]
        [StringLength(32)]
        public string PrizeDescription { get; set; }
        [Column("draw_sequence")]
        public short? DrawSequence { get; set; }
    }
}