// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("barrel_draw_ticket_eligibility")]
    public partial class BarrelDrawTicketEligibility
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("promotion_id", TypeName = "numeric(18, 0)")]
        public decimal PromotionId { get; set; }
        [Column("mins_before_draw_tickets_can_be_validated")]
        public short MinsBeforeDrawTicketsCanBeValidated { get; set; }
        [Column("validate_by_kiosk_activity_flag")]
        [StringLength(1)]
        public string ValidateByKioskActivityFlag { get; set; }
        [Column("validate_by_egm_activity_flag")]
        [StringLength(1)]
        public string ValidateByEgmActivityFlag { get; set; }
        [Column("validate_by_pos_activity_flag")]
        [StringLength(1)]
        public string ValidateByPosActivityFlag { get; set; }
        [Column("validate_by_barrel_draw_ticket_flag")]
        [StringLength(1)]
        public string ValidateByBarrelDrawTicketFlag { get; set; }
    }
}