// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("barrel_draw_ticket_summary")]
    public partial class BarrelDrawTicketSummary
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("barrel_draw_promotion_id", TypeName = "numeric(18, 0)")]
        public decimal BarrelDrawPromotionId { get; set; }
        [Key]
        [Column("patron_id", TypeName = "numeric(18, 0)")]
        public decimal PatronId { get; set; }
        [Column("ticket_count")]
        public int? TicketCount { get; set; }
        [Column("last_updated", TypeName = "datetime")]
        public DateTime? LastUpdated { get; set; }
    }
}