// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("barrel_draw_log")]
    [Index(nameof(PatronId), nameof(TicketDatetime), Name = "IX_BarrelDrawLog_PatronRecentTickets")]
    [Index(nameof(Printed), Name = "ind_bdl_status")]
    [Index(nameof(EgmSerialNumber), Name = "ind_egm_serial_number")]
    [Index(nameof(PatronId), Name = "ind_patron_id")]
    [Index(nameof(PurgeDatetime), nameof(SiteId), nameof(PromotionId), nameof(TicketNumber), Name = "ind_purge_datetime")]
    [Index(nameof(TicketDatetime), nameof(SiteId), nameof(PromotionId), nameof(TicketNumber), Name = "ind_ticket_datetime")]
    public partial class BarrelDrawLog
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("promotion_id", TypeName = "numeric(18, 0)")]
        public decimal PromotionId { get; set; }
        [Key]
        [Column("ticket_number")]
        public int TicketNumber { get; set; }
        [Column("ticket_datetime", TypeName = "datetime")]
        public DateTime TicketDatetime { get; set; }
        [Column("patron_card_id")]
        public int PatronCardId { get; set; }
        [Column("patron_id", TypeName = "numeric(18, 0)")]
        public decimal PatronId { get; set; }
        [Column("member_id")]
        public int MemberId { get; set; }
        [Column("egm_serial_number")]
        public int EgmSerialNumber { get; set; }
        [Column("criterion_id", TypeName = "numeric(18, 0)")]
        public decimal CriterionId { get; set; }
        [Required]
        [Column("printed")]
        [StringLength(1)]
        public string Printed { get; set; }
        [Column("purge_datetime", TypeName = "datetime")]
        public DateTime? PurgeDatetime { get; set; }
    }
}