// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("barrel_draw_criterion")]
    public partial class BarrelDrawCriterion
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("promotion_id", TypeName = "numeric(18, 0)")]
        public decimal PromotionId { get; set; }
        [Key]
        [Column("id", TypeName = "numeric(18, 0)")]
        public decimal Id { get; set; }
        [Required]
        [Column("enabled_flag")]
        [StringLength(1)]
        public string EnabledFlag { get; set; }
        [Required]
        [Column("criterion")]
        [StringLength(50)]
        public string Criterion { get; set; }
    }
}