// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("batch_confirm")]
    public partial class BatchConfirm
    {
        [Key]
        [Column("record_unique_id")]
        [StringLength(60)]
        public string RecordUniqueId { get; set; }
        [Key]
        [Column("sys_site_batch_confirm_type_id", TypeName = "numeric(18, 0)")]
        public decimal SysSiteBatchConfirmTypeId { get; set; }
        [Key]
        [Column("edit_datetime", TypeName = "datetime")]
        public DateTime EditDatetime { get; set; }
        [Column("identity_description")]
        [StringLength(60)]
        public string IdentityDescription { get; set; }
        [Column("system_id")]
        public byte SystemId { get; set; }
        [Column("css_site_id")]
        public short CssSiteId { get; set; }
        [Column("old_value")]
        [StringLength(255)]
        public string OldValue { get; set; }
        [Column("new_value")]
        [StringLength(255)]
        public string NewValue { get; set; }
        [Column("status")]
        [StringLength(10)]
        public string Status { get; set; }
        [Column("user_id_one")]
        [StringLength(10)]
        public string UserIdOne { get; set; }
        [Column("user_id_two")]
        [StringLength(10)]
        public string UserIdTwo { get; set; }
        [Column("last_action_datetime", TypeName = "datetime")]
        public DateTime? LastActionDatetime { get; set; }
        [Column("update_this_site_only")]
        [StringLength(1)]
        public string UpdateThisSiteOnly { get; set; }
    }
}