// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("batch_confirm_type")]
    public partial class BatchConfirmType
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("description")]
        [StringLength(30)]
        public string Description { get; set; }
        [Required]
        [Column("table_name")]
        [StringLength(35)]
        public string TableName { get; set; }
        [Required]
        [Column("column_name")]
        [StringLength(35)]
        public string ColumnName { get; set; }
    }
}