// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("campaign_patron")]
    public partial class CampaignPatron
    {
        [Key]
        [Column("campaign_id")]
        [StringLength(36)]
        public string CampaignId { get; set; }
        [Key]
        [Column("patron_id", TypeName = "numeric(18, 0)")]
        public decimal PatronId { get; set; }
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Column("redeemed_flag")]
        [StringLength(1)]
        public string RedeemedFlag { get; set; }
        [Column("notification_sent_datetime", TypeName = "datetime")]
        public DateTime? NotificationSentDatetime { get; set; }
        [Column("redeemed_datetime", TypeName = "datetime")]
        public DateTime? RedeemedDatetime { get; set; }
        [Column("eligible_start_datetime", TypeName = "datetime")]
        public DateTime? EligibleStartDatetime { get; set; }
        [Column("eligible_end_datetime", TypeName = "datetime")]
        public DateTime? EligibleEndDatetime { get; set; }
    }
}