// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("campaign")]
    public partial class Campaign
    {
        [Key]
        [Column("id")]
        [StringLength(36)]
        public string Id { get; set; }
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Column("name")]
        [StringLength(255)]
        public string Name { get; set; }
        [Column("start_datetime", TypeName = "datetime")]
        public DateTime? StartDatetime { get; set; }
        [Column("end_datetime", TypeName = "datetime")]
        public DateTime? EndDatetime { get; set; }
        [Column("active_flag")]
        [StringLength(1)]
        public string ActiveFlag { get; set; }
        [Column("kiosk_message")]
        [StringLength(255)]
        public string KioskMessage { get; set; }
        [Column("tracking_type_id")]
        public short? TrackingTypeId { get; set; }
        [Column("point_value")]
        public int? PointValue { get; set; }
        [Column("cash_value")]
        public int? CashValue { get; set; }
        [Column("ticket_text")]
        [StringLength(255)]
        public string TicketText { get; set; }
    }
}