// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("cashier_float_balance")]
    public partial class CashierFloatBalance
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("start_datetime", TypeName = "datetime")]
        public DateTime StartDatetime { get; set; }
        [Column("start_balance_actual", TypeName = "numeric(18, 0)")]
        public decimal? StartBalanceActual { get; set; }
        [Column("cash_in_amount", TypeName = "numeric(18, 0)")]
        public decimal? CashInAmount { get; set; }
        [Column("cash_out_amount", TypeName = "numeric(18, 0)")]
        public decimal? CashOutAmount { get; set; }
        [Column("gaming_cheques", TypeName = "numeric(18, 0)")]
        public decimal? GamingCheques { get; set; }
        [Column("egm_payouts", TypeName = "numeric(18, 0)")]
        public decimal? EgmPayouts { get; set; }
        [Column("tito_ticket_payouts", TypeName = "numeric(18, 0)")]
        public decimal? TitoTicketPayouts { get; set; }
        [Column("hopper_refills", TypeName = "numeric(18, 0)")]
        public decimal? HopperRefills { get; set; }
        [Column("misc_payouts", TypeName = "numeric(18, 0)")]
        public decimal? MiscPayouts { get; set; }
        [Column("my_cash_withdrawals", TypeName = "numeric(18, 0)")]
        public decimal? MyCashWithdrawals { get; set; }
        [Column("my_cash_deposits", TypeName = "numeric(18, 0)")]
        public decimal? MyCashDeposits { get; set; }
        [Column("finish_datetime", TypeName = "datetime")]
        public DateTime? FinishDatetime { get; set; }
        [Column("finish_balance_actual", TypeName = "numeric(18, 0)")]
        public decimal? FinishBalanceActual { get; set; }
        [Column("finish_balance_expected", TypeName = "numeric(18, 0)")]
        public decimal? FinishBalanceExpected { get; set; }
        [Required]
        [Column("user_id")]
        [StringLength(16)]
        public string UserId { get; set; }
    }
}