// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("cashier_float_balance_denominations")]
    public partial class CashierFloatBalanceDenominations
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("balance_datetime", TypeName = "datetime")]
        public DateTime BalanceDatetime { get; set; }
        [Key]
        [Column("cashier_denomination_id")]
        public int CashierDenominationId { get; set; }
        [Column("denomination_total", TypeName = "numeric(18, 0)")]
        public decimal DenominationTotal { get; set; }
    }
}