// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("cbg_account_qogr_limit")]
    public partial class CbgAccountQogrLimit
    {
        [Key]
        [Column("cbg_account_id", TypeName = "numeric(18, 0)")]
        public decimal CbgAccountId { get; set; }
        [Key]
        [Column("cbg_account_qogr_limit_type_id")]
        public byte CbgAccountQogrLimitTypeId { get; set; }
        [Column("amount", TypeName = "numeric(18, 0)")]
        public decimal Amount { get; set; }
        [Column("display_on_gemini_flag")]
        [StringLength(1)]
        public string DisplayOnGeminiFlag { get; set; }
    }
}