// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("cbg_audit")]
    [Index(nameof(SiteId), nameof(AuditOperationDatetime), Name = "IX_cbg_audit_siteid")]
    [Index(nameof(CbgAccountId), nameof(AuditOperationDatetime), Name = "ind_account_audit_datetime")]
    public partial class CbgAudit
    {
        [Key]
        [Column("id", TypeName = "numeric(18, 0)")]
        public decimal Id { get; set; }
        [Column("site_id")]
        public int? SiteId { get; set; }
        [Column("cbg_account_id", TypeName = "numeric(18, 0)")]
        public decimal? CbgAccountId { get; set; }
        [Column("cbg_audit_operation_id")]
        public short? CbgAuditOperationId { get; set; }
        [Column("audit_operation_datetime", TypeName = "datetime")]
        public DateTime? AuditOperationDatetime { get; set; }
        [Column("logged_datetime", TypeName = "datetime")]
        public DateTime? LoggedDatetime { get; set; }
        [Column("description")]
        [StringLength(255)]
        public string Description { get; set; }
        [Column("user_id")]
        [StringLength(16)]
        public string UserId { get; set; }
        [Column("supervisor_id")]
        [StringLength(16)]
        public string SupervisorId { get; set; }
        [Column("egm_serial_number")]
        public int? EgmSerialNumber { get; set; }
        [Column("amount_1", TypeName = "numeric(18, 0)")]
        public decimal? Amount1 { get; set; }
        [Column("amount_2", TypeName = "numeric(18, 0)")]
        public decimal? Amount2 { get; set; }
        [Column("comment_1")]
        [StringLength(255)]
        public string Comment1 { get; set; }
        [Column("comment_2")]
        [StringLength(255)]
        public string Comment2 { get; set; }
        [Column("comment_3")]
        [StringLength(255)]
        public string Comment3 { get; set; }
        [Column("comment_4")]
        [StringLength(255)]
        public string Comment4 { get; set; }
        [Column("session_id")]
        public int? SessionId { get; set; }
        [Column("device_id")]
        public int? DeviceId { get; set; }
    }
}