// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("cbg_account_cash_balance")]
    [Index(nameof(Balance), Name = "ix_cbg_account_cash_balance_balance")]
    public partial class CbgAccountCashBalance
    {
        [Key]
        [Column("cbg_account_id", TypeName = "numeric(18, 0)")]
        public decimal CbgAccountId { get; set; }
        [Required]
        [Column("balance")]
        [StringLength(16)]
        public string Balance { get; set; }
        [Column("last_updated", TypeName = "datetime")]
        public DateTime LastUpdated { get; set; }
        [Column("cash_withdrawal_balance", TypeName = "numeric(18, 0)")]
        public decimal? CashWithdrawalBalance { get; set; }
    }
}