// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("cbg_audit_operation")]
    public partial class CbgAuditOperation
    {
        [Key]
        [Column("id")]
        public short Id { get; set; }
        [Required]
        [Column("description")]
        [StringLength(50)]
        public string Description { get; set; }
        [Column("log_to_database_flag")]
        [StringLength(1)]
        public string LogToDatabaseFlag { get; set; }
        [Column("amount1_description")]
        [StringLength(255)]
        public string Amount1Description { get; set; }
        [Column("amount2_description")]
        [StringLength(255)]
        public string Amount2Description { get; set; }
        [Column("report_color")]
        [StringLength(20)]
        public string ReportColor { get; set; }
        [Column("amount1_format")]
        [StringLength(20)]
        public string Amount1Format { get; set; }
        [Column("amount2_format")]
        [StringLength(20)]
        public string Amount2Format { get; set; }
    }
}