// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("cbg_account_cash_transaction_type")]
    public partial class CbgAccountCashTransactionType
    {
        [Key]
        [Column("id")]
        public byte Id { get; set; }
        [Required]
        [Column("description")]
        [StringLength(50)]
        public string Description { get; set; }
        [Column("account_action")]
        [StringLength(1)]
        public string AccountAction { get; set; }
        [Column("sweep")]
        [StringLength(1)]
        public string Sweep { get; set; }
        [Column("purpose")]
        [StringLength(150)]
        public string Purpose { get; set; }
    }
}