// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("cbg_acc_balance_variance_summary")]
    public partial class CbgAccBalanceVarianceSummary
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("variance_datetime", TypeName = "datetime")]
        public DateTime VarianceDatetime { get; set; }
        [Key]
        [Column("cbg_account_id", TypeName = "numeric(18, 0)")]
        public decimal CbgAccountId { get; set; }
        [Column("actual_balance")]
        public int? ActualBalance { get; set; }
        [Column("expected_balance")]
        public int? ExpectedBalance { get; set; }
        [Column("variance")]
        public int? Variance { get; set; }
    }
}