// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("cbg_card_account")]
    [Index(nameof(CbgAccountId), Name = "ind_cbg_ca_account")]
    public partial class CbgCardAccount
    {
        [Key]
        [Column("card_id")]
        public int CardId { get; set; }
        [Column("cbg_account_id", TypeName = "numeric(18, 0)")]
        public decimal CbgAccountId { get; set; }
    }
}