// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("cbg_qogr_account_limits")]
    public partial class CbgQogrAccountLimits
    {
        [Key]
        [Column("cbg_qogr_account_limit_type_id")]
        public byte CbgQogrAccountLimitTypeId { get; set; }
        [Key]
        [Column("cbg_account_type_id")]
        public byte CbgAccountTypeId { get; set; }
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Column("default_amount", TypeName = "numeric(18, 0)")]
        public decimal? DefaultAmount { get; set; }
        [Column("min_amount", TypeName = "numeric(18, 0)")]
        public decimal? MinAmount { get; set; }
        [Column("max_amount", TypeName = "numeric(18, 0)")]
        public decimal? MaxAmount { get; set; }
    }
}