// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("charge_item")]
    [Index(nameof(StartDatetime), nameof(EndDatetime), nameof(Enabled), Name = "idx_dates_enabled")]
    public partial class ChargeItem
    {
        [Key]
        [Column("id", TypeName = "numeric(9, 0)")]
        public decimal Id { get; set; }
        [Column("description")]
        [StringLength(60)]
        public string Description { get; set; }
        [Column("site_id")]
        public short? SiteId { get; set; }
        [Column("gl_code")]
        [StringLength(5)]
        public string GlCode { get; set; }
        [Column("calculation_method_id")]
        public short? CalculationMethodId { get; set; }
        [Column("reference_id")]
        public int? ReferenceId { get; set; }
        [Column("rate", TypeName = "numeric(18, 6)")]
        public decimal? Rate { get; set; }
        [Column("start_datetime", TypeName = "datetime")]
        public DateTime? StartDatetime { get; set; }
        [Column("end_datetime", TypeName = "datetime")]
        public DateTime? EndDatetime { get; set; }
        [Column("enabled")]
        [StringLength(1)]
        public string Enabled { get; set; }
        [Column("units")]
        public short? Units { get; set; }
        [Column("monthly_min_charge")]
        public int? MonthlyMinCharge { get; set; }
        [Column("monthly_max_charge")]
        public int? MonthlyMaxCharge { get; set; }
        [Column("turnover_threshold_group_id")]
        public int? TurnoverThresholdGroupId { get; set; }
        [Column("sweep_frequency")]
        public short? SweepFrequency { get; set; }
        [Column("charge_type")]
        [StringLength(1)]
        public string ChargeType { get; set; }
        [Column("gst_flag")]
        [StringLength(1)]
        public string GstFlag { get; set; }
        [Column("group_description")]
        [StringLength(30)]
        public string GroupDescription { get; set; }
        [Column("eft_flag")]
        [StringLength(1)]
        public string EftFlag { get; set; }
    }
}