// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("chart_of_accounts")]
    public partial class ChartOfAccounts
    {
        [Key]
        [Column("gl_code")]
        [StringLength(5)]
        public string GlCode { get; set; }
        [Column("dept_id")]
        [StringLength(3)]
        public string DeptId { get; set; }
        [Column("description")]
        [StringLength(60)]
        public string Description { get; set; }
        [Column("report_section")]
        public short? ReportSection { get; set; }
        [Column("gst_gl_code")]
        [StringLength(5)]
        public string GstGlCode { get; set; }
    }
}