// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("charge_group_member")]
    [Index(nameof(Id), nameof(ChargeGroupId), Name = "idx_id_charge_group_id")]
    public partial class ChargeGroupMember
    {
        [Key]
        [Column("id")]
        public short Id { get; set; }
        [Column("charge_group_id")]
        public short? ChargeGroupId { get; set; }
        [Column("member_id")]
        public int? MemberId { get; set; }
    }
}