// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("charge_group")]
    [Index(nameof(Id), nameof(GroupType), Name = "idx_id_group_type")]
    public partial class ChargeGroup
    {
        [Key]
        [Column("id")]
        public short Id { get; set; }
        [Column("description")]
        [StringLength(30)]
        public string Description { get; set; }
        [Column("group_type")]
        public short? GroupType { get; set; }
        [Column("group_id")]
        public int? GroupId { get; set; }
    }
}