// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("cheque_level")]
    public partial class ChequeLevel
    {
        [Key]
        [Column("id")]
        public short Id { get; set; }
        [Column("description")]
        [StringLength(30)]
        public string Description { get; set; }
        [Column("default_days")]
        public short? DefaultDays { get; set; }
    }
}