// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("configuration_group")]
    public partial class ConfigurationGroup
    {
        [Key]
        [Column("group_name")]
        [StringLength(20)]
        public string GroupName { get; set; }
        [Key]
        [Column("item_name")]
        [StringLength(20)]
        public string ItemName { get; set; }
    }
}