// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("conrad_card_type")]
    public partial class ConradCardType
    {
        [Key]
        [Column("card_type_id")]
        public int CardTypeId { get; set; }
        [Column("conrad_card_type_id")]
        public int ConradCardTypeId { get; set; }
        [Column("conrad_description")]
        [StringLength(20)]
        public string ConradDescription { get; set; }
    }
}