// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("system")]
    public partial class CougarSystem
    {
        [Key]
        [Column("id")]
        public byte Id { get; set; }
        [Column("description")]
        [StringLength(30)]
        public string Description { get; set; }
        [Column("show_group_only_flag")]
        [StringLength(1)]
        public string ShowGroupOnlyFlag { get; set; }
    }
}