// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("country")]
    public partial class Country
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("description")]
        [StringLength(30)]
        public string Description { get; set; }
        [Column("iso_code")]
        [StringLength(10)]
        public string IsoCode { get; set; }
        [Column("currency_id")]
        public short? CurrencyId { get; set; }
        [Column("phone_prefix")]
        [StringLength(10)]
        public string PhonePrefix { get; set; }
        [Column("flag_of_country")]
        public byte[] FlagOfCountry { get; set; }
        [Column("active_flag")]
        [StringLength(1)]
        public string ActiveFlag { get; set; }
        [Column("detail_1")]
        [StringLength(255)]
        public string Detail1 { get; set; }
    }
}