// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("count_file_type")]
    public partial class CountFileType
    {
        [Key]
        [Column("id", TypeName = "numeric(18, 0)")]
        public decimal Id { get; set; }
        [Required]
        [Column("description")]
        [StringLength(30)]
        public string Description { get; set; }
        [Required]
        [Column("extension")]
        [StringLength(3)]
        public string Extension { get; set; }
        [Required]
        [Column("separator")]
        [StringLength(15)]
        public string Separator { get; set; }
        [Column("position_column")]
        public int PositionColumn { get; set; }
        [Column("denomination_column")]
        public int? DenominationColumn { get; set; }
        [Column("token_column")]
        public int? TokenColumn { get; set; }
        [Column("note_column")]
        public int? NoteColumn { get; set; }
        [Column("note_count_type")]
        [StringLength(15)]
        public string NoteCountType { get; set; }
        [Column("coin_column")]
        public int? CoinColumn { get; set; }
        [Column("coin_count_type")]
        [StringLength(15)]
        public string CoinCountType { get; set; }
        [Required]
        [Column("row_heading")]
        [StringLength(1)]
        public string RowHeading { get; set; }
    }
}