// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("css_audit")]
    [Index(nameof(AuditDatetime), nameof(CssAuditOperationId), Name = "ind_dt_css_audit_op_id")]
    [Index(nameof(AuditDatetime), nameof(CssSiteId), nameof(PatronId), Name = "ind_patron_audit_datetime")]
    public partial class CssAudit
    {
        [Key]
        [Column("id", TypeName = "numeric(18, 0)")]
        public decimal Id { get; set; }
        [Column("user_id")]
        [StringLength(10)]
        public string UserId { get; set; }
        [Column("css_audit_operation_id")]
        public short? CssAuditOperationId { get; set; }
        [Column("logged_datetime", TypeName = "datetime")]
        public DateTime? LoggedDatetime { get; set; }
        [Column("audit_datetime", TypeName = "datetime")]
        public DateTime? AuditDatetime { get; set; }
        [Column("system_id")]
        public byte? SystemId { get; set; }
        [Column("css_site_id")]
        public short? CssSiteId { get; set; }
        [Column("employee_id", TypeName = "numeric(18, 0)")]
        public decimal? EmployeeId { get; set; }
        [Column("patron_id", TypeName = "numeric(18, 0)")]
        public decimal? PatronId { get; set; }
        [Column("device_serial_number")]
        public int? DeviceSerialNumber { get; set; }
        [Column("amount_1", TypeName = "numeric(18, 0)")]
        public decimal? Amount1 { get; set; }
        [Column("amount_2", TypeName = "numeric(18, 0)")]
        public decimal? Amount2 { get; set; }
        [Column("comment_string_1")]
        [StringLength(50)]
        public string CommentString1 { get; set; }
        [Column("comment_string_2")]
        [StringLength(50)]
        public string CommentString2 { get; set; }
        [Column("comment_string_3")]
        [StringLength(50)]
        public string CommentString3 { get; set; }
        [Column("comment_string_4")]
        [StringLength(50)]
        public string CommentString4 { get; set; }
        [Column("comment_string_5")]
        [StringLength(50)]
        public string CommentString5 { get; set; }
    }
}