// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("css_audit_operation")]
    public partial class CssAuditOperation
    {
        [Key]
        [Column("id")]
        public short Id { get; set; }
        [Column("description")]
        [StringLength(40)]
        public string Description { get; set; }
        [Column("statement_flag")]
        [StringLength(1)]
        public string StatementFlag { get; set; }
    }
}