// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("database_version")]
    public partial class DatabaseVersion
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("version")]
        [StringLength(30)]
        public string Version { get; set; }
        [Column("run_count")]
        public int RunCount { get; set; }
        [Column("upgrade_datetime", TypeName = "datetime")]
        public DateTime UpgradeDatetime { get; set; }
    }
}