// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("device_history")]
    [Index(nameof(Type), Name = "ind_dh_type")]
    public partial class DeviceHistory
    {
        [Column("site_id")]
        public short SiteId { get; set; }
        [Column("egm_serial_number")]
        public int EgmSerialNumber { get; set; }
        [Required]
        [Column("type")]
        [StringLength(15)]
        public string Type { get; set; }
        [Column("date_from", TypeName = "datetime")]
        public DateTime? DateFrom { get; set; }
        [Column("date_to", TypeName = "datetime")]
        public DateTime? DateTo { get; set; }
        [Column("historical_comment")]
        [StringLength(255)]
        public string HistoricalComment { get; set; }
        [Column("historical_comment_2")]
        [StringLength(80)]
        public string HistoricalComment2 { get; set; }
        [Key]
        [Column("id", TypeName = "numeric(18, 0)")]
        public decimal Id { get; set; }
    }
}