// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("device")]
    [Index(nameof(SiteId), nameof(MidmCard), nameof(MidmPort), nameof(MidmAddress), Name = "ind_device_midm", IsUnique = true)]
    public partial class Device
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("device_number")]
        public int? DeviceNumber { get; set; }
        [Column("device_type")]
        [StringLength(15)]
        public string DeviceType { get; set; }
        [Column("description")]
        [StringLength(30)]
        public string Description { get; set; }
        [Column("location")]
        [StringLength(30)]
        public string Location { get; set; }
        [Column("midm_card")]
        public short? MidmCard { get; set; }
        [Column("midm_port")]
        public short? MidmPort { get; set; }
        [Column("midm_address")]
        public short? MidmAddress { get; set; }
        [Column("spare_1")]
        [StringLength(12)]
        public string Spare1 { get; set; }
        [Column("spare_2")]
        [StringLength(12)]
        public string Spare2 { get; set; }
    }
}