// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("drawdown_denomination")]
    public partial class DrawdownDenomination
    {
        public DrawdownDenomination()
        {
            PointsPlayDenomination = new HashSet<PointsPlayDenomination>();
        }

        [Key]
        [Column("id", TypeName = "numeric(18, 0)")]
        public decimal Id { get; set; }
        [Required]
        [Column("description")]
        [StringLength(30)]
        public string Description { get; set; }
        [Column("denomination_value")]
        public short DenominationValue { get; set; }

        [InverseProperty("DrawdownDenomination")]
        public virtual ICollection<PointsPlayDenomination> PointsPlayDenomination { get; set; }
    }
}