// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Keyless]
    [Table("eft_end_of_day_GL_mappings")]
    public partial class EftEndOfDayGLMappings
    {
        [Required]
        [Column("feeline_GL_code")]
        [StringLength(10)]
        public string FeelineGlCode { get; set; }
        [Required]
        [Column("maxgaming_GL_code")]
        [StringLength(10)]
        public string MaxgamingGlCode { get; set; }
        [Required]
        [Column("feeline_GST_GL_code")]
        [StringLength(10)]
        public string FeelineGstGlCode { get; set; }
        [Required]
        [Column("maxgaming_GST_GL_code")]
        [StringLength(10)]
        public string MaxgamingGstGlCode { get; set; }
    }
}