// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("eft_end_of_day")]
    [Index(nameof(StartDatetime), nameof(ChargeItemId), Name = "idx_sdt_chgitemid")]
    [Index(nameof(SiteId), nameof(StartDatetime), nameof(ChargeItemId), Name = "idx_site_date_charge_item")]
    [Index(nameof(StartDatetime), Name = "start_datetime")]
    public partial class EftEndOfDay
    {
        [Key]
        [Column("charge_item_id", TypeName = "numeric(13, 0)")]
        public decimal ChargeItemId { get; set; }
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("start_datetime", TypeName = "datetime")]
        public DateTime StartDatetime { get; set; }
        [Key]
        [Column("gl_code")]
        [StringLength(10)]
        public string GlCode { get; set; }
        [Column("item_name")]
        [StringLength(60)]
        public string ItemName { get; set; }
        [Column("report_section")]
        public int? ReportSection { get; set; }
        [Column("unit")]
        public int? Unit { get; set; }
        [Column("rate", TypeName = "numeric(18, 8)")]
        public decimal? Rate { get; set; }
        [Column("total")]
        public int? Total { get; set; }
        [Column("gst", TypeName = "numeric(18, 6)")]
        public decimal? Gst { get; set; }
        [Column("group_description")]
        [StringLength(30)]
        public string GroupDescription { get; set; }
        [Column("calculation_method_id")]
        public short? CalculationMethodId { get; set; }
        [Column("sweep_frequency")]
        [StringLength(1)]
        public string SweepFrequency { get; set; }
    }
}