// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("egm_clearance")]
    public partial class EgmClearance
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("clearance_type")]
        [StringLength(30)]
        public string ClearanceType { get; set; }
        [Key]
        [Column("start_datetime", TypeName = "datetime")]
        public DateTime StartDatetime { get; set; }
        [Key]
        [Column("egm_serial_number")]
        public int EgmSerialNumber { get; set; }
        [Column("egm_config_datetime", TypeName = "datetime")]
        public DateTime? EgmConfigDatetime { get; set; }
        [Column("money_box_number")]
        [StringLength(30)]
        public string MoneyBoxNumber { get; set; }
        [Column("clearance_status")]
        [StringLength(30)]
        public string ClearanceStatus { get; set; }
        [Column("end_datetime", TypeName = "datetime")]
        public DateTime? EndDatetime { get; set; }
        [Column("accepted_entry_datetime", TypeName = "datetime")]
        public DateTime? AcceptedEntryDatetime { get; set; }
        [Column("last_entry_datetime", TypeName = "datetime")]
        public DateTime? LastEntryDatetime { get; set; }
        [Column("logged_datetime", TypeName = "datetime")]
        public DateTime? LoggedDatetime { get; set; }
        [Column("comments")]
        [StringLength(255)]
        public string Comments { get; set; }
    }
}