// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("egm_clearance_summary")]
    public partial class EgmClearanceSummary
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("start_datetime", TypeName = "datetime")]
        public DateTime StartDatetime { get; set; }
        [Key]
        [Column("egm_serial_number")]
        public int EgmSerialNumber { get; set; }
        [Column("day_status")]
        [StringLength(30)]
        public string DayStatus { get; set; }
        [Column("day_end_datetime", TypeName = "datetime")]
        public DateTime? DayEndDatetime { get; set; }
        [Column("exp_coins_amt")]
        public int? ExpCoinsAmt { get; set; }
        [Column("exp_coins_cnt")]
        public int? ExpCoinsCnt { get; set; }
        [Column("exp_notes_amt")]
        public int? ExpNotesAmt { get; set; }
        [Column("exp_notes_cnt")]
        public int? ExpNotesCnt { get; set; }
        [Column("exp_notes_cnt_5")]
        public int? ExpNotesCnt5 { get; set; }
        [Column("exp_notes_cnt_10")]
        public int? ExpNotesCnt10 { get; set; }
        [Column("exp_notes_cnt_20")]
        public int? ExpNotesCnt20 { get; set; }
        [Column("exp_notes_cnt_50")]
        public int? ExpNotesCnt50 { get; set; }
        [Column("exp_notes_cnt_100")]
        public int? ExpNotesCnt100 { get; set; }
        [Column("act_coins_amt")]
        public int? ActCoinsAmt { get; set; }
        [Column("act_coins_cnt")]
        public int? ActCoinsCnt { get; set; }
        [Column("act_notes_amt")]
        public int? ActNotesAmt { get; set; }
        [Column("act_notes_cnt")]
        public int? ActNotesCnt { get; set; }
        [Column("act_notes_cnt_5")]
        public int? ActNotesCnt5 { get; set; }
        [Column("act_notes_cnt_10")]
        public int? ActNotesCnt10 { get; set; }
        [Column("act_notes_cnt_20")]
        public int? ActNotesCnt20 { get; set; }
        [Column("act_notes_cnt_50")]
        public int? ActNotesCnt50 { get; set; }
        [Column("act_notes_cnt_100")]
        public int? ActNotesCnt100 { get; set; }
        [Column("coin_hold_start_datetime", TypeName = "datetime")]
        public DateTime? CoinHoldStartDatetime { get; set; }
        [Column("coin_hold_status")]
        [StringLength(30)]
        public string CoinHoldStatus { get; set; }
        [Column("coin_hold_end_datetime", TypeName = "datetime")]
        public DateTime? CoinHoldEndDatetime { get; set; }
        [Column("note_hold_start_datetime", TypeName = "datetime")]
        public DateTime? NoteHoldStartDatetime { get; set; }
        [Column("note_hold_status")]
        [StringLength(30)]
        public string NoteHoldStatus { get; set; }
        [Column("note_hold_end_datetime", TypeName = "datetime")]
        public DateTime? NoteHoldEndDatetime { get; set; }
        [Column("hold_exp_coins_amt")]
        public int? HoldExpCoinsAmt { get; set; }
        [Column("hold_exp_coins_cnt")]
        public int? HoldExpCoinsCnt { get; set; }
        [Column("hold_exp_notes_amt")]
        public int? HoldExpNotesAmt { get; set; }
        [Column("hold_exp_notes_cnt")]
        public int? HoldExpNotesCnt { get; set; }
        [Column("hold_exp_notes_cnt_5")]
        public int? HoldExpNotesCnt5 { get; set; }
        [Column("hold_exp_notes_cnt_10")]
        public int? HoldExpNotesCnt10 { get; set; }
        [Column("hold_exp_notes_cnt_20")]
        public int? HoldExpNotesCnt20 { get; set; }
        [Column("hold_exp_notes_cnt_50")]
        public int? HoldExpNotesCnt50 { get; set; }
        [Column("hold_exp_notes_cnt_100")]
        public int? HoldExpNotesCnt100 { get; set; }
        [Column("hold_act_coins_amt")]
        public int? HoldActCoinsAmt { get; set; }
        [Column("hold_act_coins_cnt")]
        public int? HoldActCoinsCnt { get; set; }
        [Column("hold_act_notes_amt")]
        public int? HoldActNotesAmt { get; set; }
        [Column("hold_act_notes_cnt")]
        public int? HoldActNotesCnt { get; set; }
        [Column("hold_act_notes_cnt_5")]
        public int? HoldActNotesCnt5 { get; set; }
        [Column("hold_act_notes_cnt_10")]
        public int? HoldActNotesCnt10 { get; set; }
        [Column("hold_act_notes_cnt_20")]
        public int? HoldActNotesCnt20 { get; set; }
        [Column("hold_act_notes_cnt_50")]
        public int? HoldActNotesCnt50 { get; set; }
        [Column("hold_act_notes_cnt_100")]
        public int? HoldActNotesCnt100 { get; set; }
        [Column("coin_count_start_datetime", TypeName = "datetime")]
        public DateTime? CoinCountStartDatetime { get; set; }
        [Column("coin_count_status")]
        [StringLength(30)]
        public string CoinCountStatus { get; set; }
        [Column("coin_count_end_datetime", TypeName = "datetime")]
        public DateTime? CoinCountEndDatetime { get; set; }
        [Column("coin_box_number")]
        [StringLength(30)]
        public string CoinBoxNumber { get; set; }
        [Column("note_count_start_datetime", TypeName = "datetime")]
        public DateTime? NoteCountStartDatetime { get; set; }
        [Column("note_count_status")]
        [StringLength(30)]
        public string NoteCountStatus { get; set; }
        [Column("note_count_end_datetime", TypeName = "datetime")]
        public DateTime? NoteCountEndDatetime { get; set; }
        [Column("note_box_number")]
        [StringLength(30)]
        public string NoteBoxNumber { get; set; }
        [Column("coin_collections_uncounted")]
        public int? CoinCollectionsUncounted { get; set; }
        [Column("note_collections_uncounted")]
        public int? NoteCollectionsUncounted { get; set; }
        [Column("egm_config_datetime", TypeName = "datetime")]
        public DateTime? EgmConfigDatetime { get; set; }
        [Column("denomination_id")]
        public short? DenominationId { get; set; }
        [Column("game_type_id")]
        public short? GameTypeId { get; set; }
        [Column("base_game_version_number")]
        public int? BaseGameVersionNumber { get; set; }
        [Column("software_set_app_number")]
        public int? SoftwareSetAppNumber { get; set; }
        [Column("floor")]
        public short? Floor { get; set; }
        [Column("bank")]
        public short? Bank { get; set; }
        [Column("position")]
        public short? Position { get; set; }
        [Column("last_entry_datetime", TypeName = "datetime")]
        public DateTime? LastEntryDatetime { get; set; }
        [Column("logged_datetime", TypeName = "datetime")]
        public DateTime? LoggedDatetime { get; set; }
        [Column("day_comments")]
        [StringLength(255)]
        public string DayComments { get; set; }
        [Column("coin_comments")]
        [StringLength(255)]
        public string CoinComments { get; set; }
        [Column("note_comments")]
        [StringLength(255)]
        public string NoteComments { get; set; }
    }
}