// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("egm_device_configuration")]
    public partial class EgmDeviceConfiguration
    {
        [Key]
        [Column("egm_serial_number")]
        public int EgmSerialNumber { get; set; }
        [Key]
        [Column("device_type_id")]
        public short DeviceTypeId { get; set; }
        [Column("configuration_string")]
        [StringLength(50)]
        public string ConfigurationString { get; set; }
    }
}