// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("egm_downtime")]
    [Index(nameof(StartDatetime), Name = "ind_dtime_dt")]
    [Index(nameof(StartDatetime), nameof(SummaryLevel), Name = "ind_dtime_sl_dt")]
    public partial class EgmDowntime
    {
        [Key]
        [Column("egm_serial_number")]
        public int EgmSerialNumber { get; set; }
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("start_datetime", TypeName = "datetime")]
        public DateTime StartDatetime { get; set; }
        [Key]
        [Column("summary_level")]
        public short SummaryLevel { get; set; }
        [Column("minutes_down")]
        public int MinutesDown { get; set; }
        [Column("available_minutes")]
        public int AvailableMinutes { get; set; }
    }
}