// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("egm_game_meters_summary")]
    [Index(nameof(EgmSerialNumber), nameof(GameNumber), nameof(DenominationId), Name = "ind_egm_game_denom")]
    [Index(nameof(SummaryLevel), nameof(StartDatetime), nameof(EgmSerialNumber), Name = "ind_egms_e_sl_sdt")]
    [Index(nameof(StartDatetime), Name = "ind_egms_sdt")]
    [Index(nameof(SummaryLevel), Name = "ind_egms_sl")]
    [Index(nameof(SummaryLevel), nameof(StartDatetime), nameof(SiteId), Name = "ind_egms_sl_sdt_s")]
    public partial class EgmGameMetersSummary
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("egm_serial_number")]
        public int EgmSerialNumber { get; set; }
        [Key]
        [Column("denomination_id")]
        public short DenominationId { get; set; }
        [Key]
        [Column("game_number")]
        public short GameNumber { get; set; }
        [Key]
        [Column("game_variation_number")]
        public int GameVariationNumber { get; set; }
        [Key]
        [Column("summary_level")]
        public short SummaryLevel { get; set; }
        [Key]
        [Column("start_datetime", TypeName = "datetime")]
        public DateTime StartDatetime { get; set; }
        [Column("record_count")]
        public int? RecordCount { get; set; }
        [Column("stroke")]
        public int? Stroke { get; set; }
        [Column("turnover")]
        public int? Turnover { get; set; }
        [Column("wins")]
        public int? Wins { get; set; }
        [Column("progressive_wins")]
        public int? ProgressiveWins { get; set; }
        [Column("total_games_won")]
        public int? TotalGamesWon { get; set; }
        [Key]
        [Column("game_version_number")]
        public int GameVersionNumber { get; set; }
        [Key]
        [Column("software_set_approval_number")]
        public int SoftwareSetApprovalNumber { get; set; }

        [ForeignKey(nameof(SiteId))]
        [InverseProperty("EgmGameMetersSummary")]
        public virtual Site Site { get; set; }
    }
}