// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("egm_game_performance_summary")]
    public partial class EgmGamePerformanceSummary
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("egm_serial_number")]
        public int EgmSerialNumber { get; set; }
        [Key]
        [Column("summary_level")]
        public short SummaryLevel { get; set; }
        [Key]
        [Column("start_datetime", TypeName = "datetime")]
        public DateTime StartDatetime { get; set; }
        [Key]
        [Column("denomination_id")]
        public short DenominationId { get; set; }
        [Key]
        [Column("ssan")]
        public int Ssan { get; set; }
        [Key]
        [Column("game_version_number")]
        public int GameVersionNumber { get; set; }
        [Key]
        [Column("rtp")]
        public short Rtp { get; set; }
        [Key]
        [Column("floor")]
        public short Floor { get; set; }
        [Key]
        [Column("bank")]
        public short Bank { get; set; }
        [Key]
        [Column("position")]
        public short Position { get; set; }
        [Column("stroke")]
        public int? Stroke { get; set; }
        [Column("turnover")]
        public int? Turnover { get; set; }
        [Column("wins")]
        public int? Wins { get; set; }
        [Column("lp_wins")]
        public int? LpWins { get; set; }
        [Column("erp_wins")]
        public int? ErpWins { get; set; }
    }
}