// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("egm_network_limit")]
    public partial class EgmNetworkLimit
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("description")]
        [StringLength(30)]
        public string Description { get; set; }
        [Column("max_denomination")]
        public int? MaxDenomination { get; set; }
        [Column("min_rtp")]
        public int? MinRtp { get; set; }
        [Column("max_rtp")]
        public int? MaxRtp { get; set; }
        [Column("max_standard_deviation")]
        public int? MaxStandardDeviation { get; set; }
        [Column("max_lines")]
        public int? MaxLines { get; set; }
        [Column("max_bet_per_play")]
        public int? MaxBetPerPlay { get; set; }
        [Column("max_np_win")]
        public int? MaxNpWin { get; set; }
        [Column("max_progressive_win")]
        public int? MaxProgressiveWin { get; set; }
        [Column("max_ect")]
        public int? MaxEct { get; set; }
    }
}