// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("egm_protocol")]
    public partial class EgmProtocol
    {
        [Key]
        [Column("protocol_name")]
        [StringLength(8)]
        public string ProtocolName { get; set; }
        [Key]
        [Column("protocol_version")]
        [StringLength(8)]
        public string ProtocolVersion { get; set; }
        [Column("comms_label")]
        public int? CommsLabel { get; set; }
    }
}