// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("egm_revenue_summary")]
    public partial class EgmRevenueSummary
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("start_datetime", TypeName = "datetime")]
        public DateTime StartDatetime { get; set; }
        [Key]
        [Column("summary_level")]
        public short SummaryLevel { get; set; }
        [Key]
        [Column("egm_serial_number")]
        public int EgmSerialNumber { get; set; }
        [Key]
        [Column("egm_config_datetime", TypeName = "datetime")]
        public DateTime EgmConfigDatetime { get; set; }
        [Column("record_count")]
        public int? RecordCount { get; set; }
        [Column("exp_stroke_cnt")]
        public int? ExpStrokeCnt { get; set; }
        [Column("exp_turnover_amt")]
        public int? ExpTurnoverAmt { get; set; }
        [Column("exp_wins_amt")]
        public int? ExpWinsAmt { get; set; }
        [Column("exp_cancelled_credits_amt")]
        public int? ExpCancelledCreditsAmt { get; set; }
        [Column("exp_hopper_fills_amt")]
        public int? ExpHopperFillsAmt { get; set; }
        [Column("exp_cents_in_amt")]
        public int? ExpCentsInAmt { get; set; }
        [Column("exp_cents_out_amt")]
        public int? ExpCentsOutAmt { get; set; }
        [Column("exp_coins_in_cnt")]
        public int? ExpCoinsInCnt { get; set; }
        [Column("exp_coins_out_cnt")]
        public int? ExpCoinsOutCnt { get; set; }
        [Column("exp_cashless_credit_in_amt")]
        public int? ExpCashlessCreditInAmt { get; set; }
        [Column("exp_cashless_credit_out_amt")]
        public int? ExpCashlessCreditOutAmt { get; set; }
        [Column("exp_coins_to_dropbucket_amt")]
        public int? ExpCoinsToDropbucketAmt { get; set; }
        [Column("exp_coins_to_dropbucket_cnt")]
        public int? ExpCoinsToDropbucketCnt { get; set; }
        [Column("exp_notes_in_amt")]
        public int? ExpNotesInAmt { get; set; }
        [Column("exp_notes_in_cnt")]
        public int? ExpNotesInCnt { get; set; }
        [Column("exp_notes_in_cnt_5")]
        public int? ExpNotesInCnt5 { get; set; }
        [Column("exp_notes_in_cnt_10")]
        public int? ExpNotesInCnt10 { get; set; }
        [Column("exp_notes_in_cnt_20")]
        public int? ExpNotesInCnt20 { get; set; }
        [Column("exp_notes_in_cnt_50")]
        public int? ExpNotesInCnt50 { get; set; }
        [Column("exp_notes_in_cnt_100")]
        public int? ExpNotesInCnt100 { get; set; }
        [Column("exp_short_pays_amt")]
        public int? ExpShortPaysAmt { get; set; }
        [Column("exp_jackpots_amt")]
        public int? ExpJackpotsAmt { get; set; }
        [Column("exp_sap_wins_amt")]
        public int? ExpSapWinsAmt { get; set; }
        [Column("exp_lp_wins_amt")]
        public int? ExpLpWinsAmt { get; set; }
        [Column("exp_residual_turnover_amt")]
        public int? ExpResidualTurnoverAmt { get; set; }
        [Column("exp_residual_wins_amt")]
        public int? ExpResidualWinsAmt { get; set; }
        [Column("exp_ticket_printer_out_amt")]
        public int? ExpTicketPrinterOutAmt { get; set; }
        [Column("exp_gaming_cheques_amt")]
        public int? ExpGamingChequesAmt { get; set; }
        [Column("act_cancelled_credits_amt")]
        public int? ActCancelledCreditsAmt { get; set; }
        [Column("act_hopper_fills_amt")]
        public int? ActHopperFillsAmt { get; set; }
        [Column("act_coins_to_dropbucket_amt")]
        public int? ActCoinsToDropbucketAmt { get; set; }
        [Column("act_coins_to_dropbucket_cnt")]
        public int? ActCoinsToDropbucketCnt { get; set; }
        [Column("act_notes_in_amt")]
        public int? ActNotesInAmt { get; set; }
        [Column("act_notes_in_cnt")]
        public int? ActNotesInCnt { get; set; }
        [Column("act_notes_in_cnt_5")]
        public int? ActNotesInCnt5 { get; set; }
        [Column("act_notes_in_cnt_10")]
        public int? ActNotesInCnt10 { get; set; }
        [Column("act_notes_in_cnt_20")]
        public int? ActNotesInCnt20 { get; set; }
        [Column("act_notes_in_cnt_50")]
        public int? ActNotesInCnt50 { get; set; }
        [Column("act_notes_in_cnt_100")]
        public int? ActNotesInCnt100 { get; set; }
        [Column("act_short_pays_amt")]
        public int? ActShortPaysAmt { get; set; }
        [Column("act_jackpots_amt")]
        public int? ActJackpotsAmt { get; set; }
        [Column("act_sap_wins_amt")]
        public int? ActSapWinsAmt { get; set; }
        [Column("act_lp_wins_amt")]
        public int? ActLpWinsAmt { get; set; }
        [Column("denomination_id")]
        public short? DenominationId { get; set; }
        [Column("game_type_id")]
        public short? GameTypeId { get; set; }
        [Column("base_game_version_number")]
        public int? BaseGameVersionNumber { get; set; }
        [Column("software_set_app_number")]
        public int? SoftwareSetAppNumber { get; set; }
        [Column("floor")]
        public short? Floor { get; set; }
        [Column("bank")]
        public short? Bank { get; set; }
        [Column("position")]
        public short? Position { get; set; }
    }
}