// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("egm_transaction_history")]
    [Index(nameof(EgmSerialNumber), Name = "ind_egm_serial_number")]
    [Index(nameof(EmployeeId), Name = "ind_employee_id")]
    [Index(nameof(TicketNumber), Name = "ind_ticket_number")]
    [Index(nameof(TransactionDatetime), Name = "ind_trans_datetime")]
    public partial class EgmTransactionHistory
    {
        [Key]
        [Column("site_id")]
        public int SiteId { get; set; }
        [Key]
        [Column("ticket_number", TypeName = "numeric(12, 0)")]
        public decimal TicketNumber { get; set; }
        [Key]
        [Column("egm_serial_number")]
        public int EgmSerialNumber { get; set; }
        [Key]
        [Column("transaction_datetime", TypeName = "datetime")]
        public DateTime TransactionDatetime { get; set; }
        [Key]
        [Column("last_action_datetime", TypeName = "datetime")]
        public DateTime LastActionDatetime { get; set; }
        [Key]
        [Column("transaction_status")]
        [StringLength(20)]
        public string TransactionStatus { get; set; }
        [Column("employee_id", TypeName = "numeric(18, 0)")]
        public decimal? EmployeeId { get; set; }
        [Column("location")]
        [StringLength(20)]
        public string Location { get; set; }
    }
}