// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("egm_template")]
    [Index(nameof(Cabinet), Name = "ind_temp_cabinet")]
    [Index(nameof(Type), Name = "ind_temp_type")]
    public partial class EgmTemplate
    {
        [Key]
        [Column("id")]
        public short Id { get; set; }
        [Required]
        [Column("cabinet")]
        [StringLength(30)]
        public string Cabinet { get; set; }
        [Column("manufacturer_id")]
        public short? ManufacturerId { get; set; }
        [Required]
        [Column("type")]
        [StringLength(30)]
        public string Type { get; set; }
        [Column("high_win")]
        public int? HighWin { get; set; }
        [Column("high_credit")]
        public int? HighCredit { get; set; }
        [Column("max_pay")]
        public int? MaxPay { get; set; }
        [Column("drop_full")]
        public int? DropFull { get; set; }
        [Column("drop_choked")]
        public int? DropChoked { get; set; }
        [Column("hopper_fill")]
        public int? HopperFill { get; set; }
        [Column("doubleup_max")]
        public int? DoubleupMax { get; set; }
        [Column("double_limit")]
        public int? DoubleLimit { get; set; }
        [Column("denomination_id")]
        public short? DenominationId { get; set; }
        [Column("token_id")]
        public short? TokenId { get; set; }
        [Column("ticket_collect_limit")]
        public int? TicketCollectLimit { get; set; }
        [Column("valid_notes_flag")]
        [StringLength(4)]
        public string ValidNotesFlag { get; set; }
        [Column("max_games")]
        public short? MaxGames { get; set; }
        [Column("protocol")]
        [StringLength(8)]
        public string Protocol { get; set; }
        [Column("protocol_version")]
        [StringLength(8)]
        public string ProtocolVersion { get; set; }
        [Column("note_acceptor_present")]
        [StringLength(1)]
        public string NoteAcceptorPresent { get; set; }
        [Column("note_acceptor_enabled")]
        [StringLength(1)]
        public string NoteAcceptorEnabled { get; set; }
        [Column("bill_5_enabled")]
        [StringLength(1)]
        public string Bill5Enabled { get; set; }
        [Column("bill_10_enabled")]
        [StringLength(1)]
        public string Bill10Enabled { get; set; }
        [Column("bill_20_enabled")]
        [StringLength(1)]
        public string Bill20Enabled { get; set; }
        [Column("bill_50_enabled")]
        [StringLength(1)]
        public string Bill50Enabled { get; set; }
        [Column("bill_100_enabled")]
        [StringLength(1)]
        public string Bill100Enabled { get; set; }
        [Column("max_meter_value")]
        public int? MaxMeterValue { get; set; }
        [Column("max_allowable_increment")]
        public int? MaxAllowableIncrement { get; set; }
        [Column("base_game_version_number")]
        public int? BaseGameVersionNumber { get; set; }
        [Column("program_signature_timeout")]
        public short? ProgramSignatureTimeout { get; set; }
        [Column("touch_screen_present")]
        [StringLength(1)]
        public string TouchScreenPresent { get; set; }
        [Column("coin_acceptor_present")]
        [StringLength(1)]
        public string CoinAcceptorPresent { get; set; }
        [Column("hopper_present")]
        [StringLength(1)]
        public string HopperPresent { get; set; }
        [Column("ticket_printer_present")]
        [StringLength(1)]
        public string TicketPrinterPresent { get; set; }
        [Column("player_tracking_installed")]
        [StringLength(1)]
        public string PlayerTrackingInstalled { get; set; }
        [Column("software_set_app_number")]
        [StringLength(10)]
        public string SoftwareSetAppNumber { get; set; }
        [Column("spare_1")]
        [StringLength(30)]
        public string Spare1 { get; set; }
        [Column("spare_2")]
        [StringLength(30)]
        public string Spare2 { get; set; }
        [Column("spare_3")]
        [StringLength(30)]
        public string Spare3 { get; set; }
        [Column("spare_4")]
        [StringLength(30)]
        public string Spare4 { get; set; }
        [Column("spare_5")]
        [StringLength(30)]
        public string Spare5 { get; set; }
        [Column("egm_meters_limit_type")]
        [StringLength(30)]
        public string EgmMetersLimitType { get; set; }
        [Column("np_win_payout_threshold")]
        public int? NpWinPayoutThreshold { get; set; }
        [Column("sap_win_payout_threshold")]
        public int? SapWinPayoutThreshold { get; set; }
        [Column("ticket_in_device_present")]
        [StringLength(1)]
        public string TicketInDevicePresent { get; set; }
        [Column("aux_display_device_present")]
        [StringLength(1)]
        public string AuxDisplayDevicePresent { get; set; }
        [Column("mechanical_meters_present")]
        [StringLength(1)]
        public string MechanicalMetersPresent { get; set; }
        [Column("denom_hot_switching_enabled")]
        [StringLength(1)]
        public string DenomHotSwitchingEnabled { get; set; }
        [Column("var_hot_switching_enabled")]
        [StringLength(1)]
        public string VarHotSwitchingEnabled { get; set; }
        [Column("shared_prog_jackpots_enabled")]
        [StringLength(1)]
        public string SharedProgJackpotsEnabled { get; set; }
    }
}