// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("equation")]
    public partial class Equation
    {
        [Key]
        [Column("id", TypeName = "numeric(18, 0)")]
        public decimal Id { get; set; }
        [Column("system_id")]
        public byte? SystemId { get; set; }
        [Column("css_site_id")]
        public short? CssSiteId { get; set; }
        [Column("tracking_type_id")]
        public byte TrackingTypeId { get; set; }
        [Column("description")]
        [StringLength(30)]
        public string Description { get; set; }
        [Column("expression")]
        [StringLength(255)]
        public string Expression { get; set; }
        [Column("method_type")]
        [StringLength(1)]
        public string MethodType { get; set; }
        [Column("enabled_flag")]
        [StringLength(1)]
        public string EnabledFlag { get; set; }
    }
}