// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("event_type")]
    public partial class EventType
    {
        [Key]
        [Column("id")]
        public short Id { get; set; }
        [Column("description")]
        [StringLength(150)]
        public string Description { get; set; }
        [Column("source")]
        [StringLength(8)]
        public string Source { get; set; }
        [Column("event_external_id")]
        public short EventExternalId { get; set; }
        [Column("purgeable_event_flag")]
        [StringLength(1)]
        public string PurgeableEventFlag { get; set; }
    }
}