// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("file_store")]
    public partial class FileStore
    {
        [Key]
        [Column("file_name")]
        [StringLength(50)]
        public string FileName { get; set; }
        [Key]
        [Column("version")]
        [StringLength(20)]
        public string Version { get; set; }
        [Column("download_complete_datetime", TypeName = "datetime")]
        public DateTime? DownloadCompleteDatetime { get; set; }
        [Column("status")]
        [StringLength(1)]
        public string Status { get; set; }
    }
}