// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Keyless]
    [Table("file_dependence")]
    public partial class FileDependence
    {
        [Required]
        [Column("file_name")]
        [StringLength(50)]
        public string FileName { get; set; }
        [Column("version")]
        [StringLength(20)]
        public string Version { get; set; }
        [Required]
        [Column("dependence")]
        [StringLength(50)]
        public string Dependence { get; set; }
    }
}