// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("file_distribution")]
    public partial class FileDistribution
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("working_set_name")]
        [StringLength(30)]
        public string WorkingSetName { get; set; }
        [Key]
        [Column("working_set_type")]
        [StringLength(10)]
        public string WorkingSetType { get; set; }
        [Column("start_datetime", TypeName = "datetime")]
        public DateTime? StartDatetime { get; set; }
        [Column("started_datetime", TypeName = "datetime")]
        public DateTime? StartedDatetime { get; set; }
        [Column("download_complete_datetime", TypeName = "datetime")]
        public DateTime? DownloadCompleteDatetime { get; set; }
        [Column("download_started_datetime", TypeName = "datetime")]
        public DateTime? DownloadStartedDatetime { get; set; }
    }
}