// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("floor_view_master")]
    public partial class FloorViewMaster
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("floor_number")]
        public short FloorNumber { get; set; }
        [Column("floor_image")]
        public byte[] FloorImage { get; set; }
        [Column("image_width")]
        public int? ImageWidth { get; set; }
        [Column("image_height")]
        public int? ImageHeight { get; set; }
        [Column("object_width")]
        public int? ObjectWidth { get; set; }
        [Column("object_height")]
        public int? ObjectHeight { get; set; }
        [Column("floor_map_file")]
        [StringLength(255)]
        public string FloorMapFile { get; set; }
    }
}