// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("floor_control_loop_config")]
    public partial class FloorControlLoopConfig
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("loop_name")]
        [StringLength(8)]
        public string LoopName { get; set; }
        [Column("floor_control_name")]
        [StringLength(8)]
        public string FloorControlName { get; set; }
        [Column("loop_type")]
        [StringLength(8)]
        public string LoopType { get; set; }
    }
}