// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("game_variation")]
    public partial class GameVariation
    {
        [Key]
        [Column("game_type_id")]
        public int GameTypeId { get; set; }
        [Key]
        [Column("game_variation_number")]
        public int GameVariationNumber { get; set; }
        [Column("return_to_player")]
        public int ReturnToPlayer { get; set; }
    }
}