// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("id_control")]
    public partial class IdControl
    {
        [Key]
        [Column("table_name")]
        [StringLength(30)]
        public string TableName { get; set; }
        [Key]
        [Column("column_name")]
        [StringLength(30)]
        public string ColumnName { get; set; }
        [Column("id_value")]
        public int? IdValue { get; set; }
    }
}