// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("identification_item")]
    public partial class IdentificationItem
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("identification_group_id")]
        public short IdentificationGroupId { get; set; }
        [Column("description")]
        [StringLength(150)]
        public string Description { get; set; }
        [Column("point_value")]
        public short? PointValue { get; set; }
        [Column("form_section")]
        [StringLength(15)]
        public string FormSection { get; set; }
    }
}