// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("IGT_licensed_software")]
    public partial class IGTLicensedSoftware
    {
        [Key]
        [Column("software_set_app_number")]
        [StringLength(10)]
        public string SoftwareSetAppNumber { get; set; }
    }
}