// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("jackpot_pool_site_status_history")]
    public partial class JackpotPoolSiteStatusHistory
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("logged_datetime", TypeName = "datetime")]
        public DateTime LoggedDatetime { get; set; }
        [Column("site_id")]
        public short SiteId { get; set; }
        [Column("pool_number")]
        public int PoolNumber { get; set; }
        [Column("status")]
        [StringLength(1)]
        public string Status { get; set; }
    }
}