// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("jackpot_pool_group_levels")]
    public partial class JackpotPoolGroupLevels
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("jackpot_pool_group_id")]
        public short JackpotPoolGroupId { get; set; }
        [Key]
        [Column("level_number")]
        public short LevelNumber { get; set; }
        [Column("pool_site_id")]
        public short? PoolSiteId { get; set; }
        [Column("pool_number")]
        public int? PoolNumber { get; set; }
    }
}