// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("jackpot_values")]
    public partial class JackpotValues
    {
        [Key]
        [Column("id", TypeName = "numeric(18, 0)")]
        public decimal Id { get; set; }
        [Column("site_id")]
        public short? SiteId { get; set; }
        [Column("snapshot_datetime", TypeName = "datetime")]
        public DateTime? SnapshotDatetime { get; set; }
        [Column("current_value")]
        public int? CurrentValue { get; set; }
        [Column("pool_number")]
        public int? PoolNumber { get; set; }
        [Column("egm_serial_number")]
        public int? EgmSerialNumber { get; set; }
        [Column("progressive_level")]
        public short? ProgressiveLevel { get; set; }
    }
}