// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("jackpot_pool_contributions")]
    public partial class JackpotPoolContributions
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("pool_number")]
        public int PoolNumber { get; set; }
        [Key]
        [Column("fcc_site_id")]
        public short FccSiteId { get; set; }
        [Key]
        [Column("fcc_name")]
        [StringLength(10)]
        public string FccName { get; set; }
        [Column("current_amount")]
        public int? CurrentAmount { get; set; }
        [Column("last_ref_amount")]
        public int? LastRefAmount { get; set; }
        [Column("overflow", TypeName = "numeric(18, 0)")]
        public decimal? Overflow { get; set; }
    }
}