// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("jackpot_deltas_suspended")]
    public partial class JackpotDeltasSuspended
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("logged_datetime", TypeName = "datetime")]
        public DateTime LoggedDatetime { get; set; }
        [Column("site_id")]
        public short? SiteId { get; set; }
        [Column("pool_number")]
        public int? PoolNumber { get; set; }
        [Column("pool_site_id")]
        public short? PoolSiteId { get; set; }
        [Column("start_datetime", TypeName = "datetime")]
        public DateTime? StartDatetime { get; set; }
        [Column("summary_level")]
        public short? SummaryLevel { get; set; }
        [Column("egm_serial_number")]
        public int? EgmSerialNumber { get; set; }
        [Column("denomination_id")]
        public short? DenominationId { get; set; }
        [Column("ssan")]
        public int? Ssan { get; set; }
        [Column("bgvn")]
        public int? Bgvn { get; set; }
        [Column("floor")]
        public short? Floor { get; set; }
        [Column("bank")]
        public short? Bank { get; set; }
        [Column("position")]
        public short? Position { get; set; }
        [Column("pool_group_id")]
        public short? PoolGroupId { get; set; }
        [Column("total_rtp")]
        public double? TotalRtp { get; set; }
        [Column("increment")]
        public double? Increment { get; set; }
        [Column("reset")]
        public int? Reset { get; set; }
        [Column("maximum")]
        public int? Maximum { get; set; }
        [Column("turnover")]
        public int? Turnover { get; set; }
        [Column("wins")]
        public int? Wins { get; set; }
        [Column("lp_wins")]
        public int? LpWins { get; set; }
        [Column("sap_wins")]
        public int? SapWins { get; set; }
        [Column("erp_wins")]
        public int? ErpWins { get; set; }
        [Column("error_code")]
        public int? ErrorCode { get; set; }
    }
}