// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("keno_agency_reconcile")]
    public partial class KenoAgencyReconcile
    {
        [Key]
        [Column("reconcile_day")]
        public int ReconcileDay { get; set; }
        [Key]
        [Column("css_site_id")]
        public short CssSiteId { get; set; }
        [Column("logged_datetime", TypeName = "datetime")]
        public DateTime LoggedDatetime { get; set; }
        [Column("cash_deposit")]
        public int CashDeposit { get; set; }
        [Column("cash_withdrawal")]
        public int CashWithdrawal { get; set; }
        [Column("bet")]
        public int Bet { get; set; }
        [Column("win")]
        public int Win { get; set; }
        [Column("cancelled")]
        public int Cancelled { get; set; }
    }
}