// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("loop_device_application")]
    public partial class LoopDeviceApplication
    {
        [Key]
        [Column("system_id")]
        public byte SystemId { get; set; }
        [Key]
        [Column("css_site_id")]
        public short CssSiteId { get; set; }
        [Key]
        [Column("hardware_device_id")]
        public byte HardwareDeviceId { get; set; }
        [Key]
        [Column("application_id")]
        [StringLength(32)]
        public string ApplicationId { get; set; }
        [Column("weighting")]
        public int Weighting { get; set; }
        [Required]
        [Column("image_name")]
        [StringLength(30)]
        public string ImageName { get; set; }
    }
}