// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("maxbonus_ticket")]
    [Index(nameof(SiteId), nameof(CreationDatetime), Name = "ind_maxbonus_ticket")]
    public partial class MaxbonusTicket
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("promotion_name")]
        [StringLength(255)]
        public string PromotionName { get; set; }
        [Column("promotion_criteria")]
        [StringLength(255)]
        public string PromotionCriteria { get; set; }
        [Column("promotion_prize")]
        [StringLength(255)]
        public string PromotionPrize { get; set; }
        [Column("creation_datetime", TypeName = "datetime")]
        public DateTime? CreationDatetime { get; set; }
        [Column("location_floor")]
        public short? LocationFloor { get; set; }
        [Column("location_bank")]
        public short? LocationBank { get; set; }
        [Column("location_position")]
        public short? LocationPosition { get; set; }
        [Column("egm_serial_number")]
        public int? EgmSerialNumber { get; set; }
        [Column("expiry_datetime", TypeName = "datetime")]
        public DateTime? ExpiryDatetime { get; set; }
    }
}