// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("max_change_request_detail")]
    public partial class MaxChangeRequestDetail
    {
        [Key]
        [Column("id")]
        [StringLength(36)]
        public string Id { get; set; }
        [Column("site_id")]
        public short SiteId { get; set; }
        [Required]
        [Column("max_change_request_id")]
        [StringLength(36)]
        public string MaxChangeRequestId { get; set; }
        [Required]
        [Column("max_change_game_config_id")]
        [StringLength(36)]
        public string MaxChangeGameConfigId { get; set; }
        [Column("day_of_week")]
        public byte? DayOfWeek { get; set; }
        [Column("change_datetime", TypeName = "datetime")]
        public DateTime? ChangeDatetime { get; set; }
    }
}