// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("max_change_request")]
    public partial class MaxChangeRequest
    {
        [Key]
        [Column("id")]
        [StringLength(36)]
        public string Id { get; set; }
        [Column("site_id")]
        public short SiteId { get; set; }
        [Column("egm_serial_number")]
        public int EgmSerialNumber { get; set; }
        [Column("manufacturer_id")]
        public byte ManufacturerId { get; set; }
        [Column("max_change_request_type_id")]
        public byte MaxChangeRequestTypeId { get; set; }
    }
}