// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("max_change_request_type")]
    public partial class MaxChangeRequestType
    {
        [Key]
        [Column("id")]
        public byte Id { get; set; }
        [Column("description")]
        [StringLength(36)]
        public string Description { get; set; }
    }
}