// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("membership_receipts")]
    public partial class MembershipReceipts
    {
        [Key]
        [Column("css_site_id")]
        public short CssSiteId { get; set; }
        [Key]
        [Column("receipt_id", TypeName = "numeric(18, 0)")]
        public decimal ReceiptId { get; set; }
        [Key]
        [Column("receipt_datetime", TypeName = "datetime")]
        public DateTime ReceiptDatetime { get; set; }
        [Key]
        [Column("patron_id", TypeName = "numeric(18, 0)")]
        public decimal PatronId { get; set; }
        [Column("membership_id")]
        public int? MembershipId { get; set; }
        [Column("membership_type_id")]
        public int? MembershipTypeId { get; set; }
        [Column("user_id")]
        [StringLength(10)]
        public string UserId { get; set; }
        [Column("cash_amount")]
        public int? CashAmount { get; set; }
        [Column("cheque_amount")]
        public int? ChequeAmount { get; set; }
        [Column("cheque_details")]
        [StringLength(50)]
        public string ChequeDetails { get; set; }
        [Column("card_amount")]
        public int? CardAmount { get; set; }
        [Column("card_id")]
        public int? CardId { get; set; }
        [Column("total_amount")]
        public int? TotalAmount { get; set; }
        [Column("parent_patron_id", TypeName = "numeric(18, 0)")]
        public decimal? ParentPatronId { get; set; }
        [Column("status")]
        [StringLength(10)]
        public string Status { get; set; }
    }
}