// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("money_box")]
    public partial class MoneyBox
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("box_number")]
        [StringLength(30)]
        public string BoxNumber { get; set; }
        [Column("type")]
        [StringLength(30)]
        public string Type { get; set; }
        [Column("weight")]
        public int? Weight { get; set; }
        [Column("datetime_calibrated", TypeName = "datetime")]
        public DateTime? DatetimeCalibrated { get; set; }
        [Column("count_clearance_start_datetime", TypeName = "datetime")]
        public DateTime? CountClearanceStartDatetime { get; set; }
        [Column("egm_serial_number")]
        public int? EgmSerialNumber { get; set; }
        [Column("comments")]
        [StringLength(255)]
        public string Comments { get; set; }
    }
}