// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("network_device_event")]
    public partial class NetworkDeviceEvent
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("event_datetime", TypeName = "datetime")]
        public DateTime EventDatetime { get; set; }
        [Key]
        [Column("network_device_id", TypeName = "numeric(18, 0)")]
        public decimal NetworkDeviceId { get; set; }
        [Key]
        [Column("event_category_id")]
        public short EventCategoryId { get; set; }
        [Key]
        [Column("logged_datetime", TypeName = "datetime")]
        public DateTime LoggedDatetime { get; set; }
        [Required]
        [Column("event_description")]
        [StringLength(255)]
        public string EventDescription { get; set; }
        [Column("amount")]
        public int Amount { get; set; }
        [Required]
        [Column("user_id")]
        [StringLength(10)]
        public string UserId { get; set; }
    }
}