// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("network_device_transaction")]
    [Index(nameof(TransactionId), nameof(CbgAccountId), nameof(NetworkDeviceTypeId), Name = "ind_network_device_transaction_account_devicetype")]
    [Index(nameof(NetworkDeviceTypeId), Name = "ind_network_device_transaction_deviceType")]
    public partial class NetworkDeviceTransaction
    {
        [Key]
        [Column("site_id")]
        public int SiteId { get; set; }
        [Key]
        [Column("network_device_id", TypeName = "numeric(18, 0)")]
        public decimal NetworkDeviceId { get; set; }
        [Key]
        [Column("transaction_datetime", TypeName = "datetime")]
        public DateTime TransactionDatetime { get; set; }
        [Key]
        [Column("transaction_id", TypeName = "numeric(18, 0)")]
        public decimal TransactionId { get; set; }
        [Column("network_device_transaction_type_id")]
        public int NetworkDeviceTransactionTypeId { get; set; }
        [Column("ticket_number", TypeName = "numeric(12, 0)")]
        public decimal? TicketNumber { get; set; }
        [Column("egm_serial_number")]
        public int? EgmSerialNumber { get; set; }
        [Column("cbg_account_id", TypeName = "numeric(18, 0)")]
        public decimal? CbgAccountId { get; set; }
        [Column("card_id")]
        public int? CardId { get; set; }
        [Column("amount", TypeName = "numeric(18, 0)")]
        public decimal Amount { get; set; }
        [Column("user_id")]
        [StringLength(10)]
        public string UserId { get; set; }
        [Column("network_device_type_id")]
        public int? NetworkDeviceTypeId { get; set; }
        [Column("network_device_description")]
        [StringLength(50)]
        public string NetworkDeviceDescription { get; set; }
        [Column("barcode", TypeName = "numeric(18, 0)")]
        public decimal? Barcode { get; set; }
    }
}