// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("network_device")]
    public partial class NetworkDevice
    {
        [Key]
        [Column("id", TypeName = "numeric(18, 0)")]
        public decimal Id { get; set; }
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Column("network_device_type_id")]
        public int NetworkDeviceTypeId { get; set; }
        [Required]
        [Column("description")]
        [StringLength(50)]
        public string Description { get; set; }
        [Required]
        [Column("network_address")]
        [StringLength(30)]
        public string NetworkAddress { get; set; }
        [Column("floor")]
        public short Floor { get; set; }
        [Column("bank")]
        public short Bank { get; set; }
        [Required]
        [Column("location")]
        [StringLength(50)]
        public string Location { get; set; }
        [Required]
        [Column("configuration")]
        [StringLength(255)]
        public string Configuration { get; set; }
        [Required]
        [Column("enabled")]
        [StringLength(1)]
        public string Enabled { get; set; }
        [Required]
        [Column("downloadable")]
        [StringLength(1)]
        public string Downloadable { get; set; }
        [Column("x")]
        public short X { get; set; }
        [Column("y")]
        public short Y { get; set; }
        [Column("serial_number")]
        public int SerialNumber { get; set; }
        [Required]
        [Column("security_id")]
        [StringLength(16)]
        public string SecurityId { get; set; }
    }
}