// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("note_count")]
    public partial class NoteCount
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("entry_datetime", TypeName = "datetime")]
        public DateTime EntryDatetime { get; set; }
        [Key]
        [Column("money_box_number")]
        [StringLength(30)]
        public string MoneyBoxNumber { get; set; }
        [Column("egm_serial_number")]
        public int? EgmSerialNumber { get; set; }
        [Column("count_status")]
        [StringLength(30)]
        public string CountStatus { get; set; }
        [Column("notes_in_amt")]
        public int? NotesInAmt { get; set; }
        [Column("notes_in_cnt")]
        public int? NotesInCnt { get; set; }
        [Column("notes_in_cnt_5")]
        public int? NotesInCnt5 { get; set; }
        [Column("notes_in_cnt_10")]
        public int? NotesInCnt10 { get; set; }
        [Column("notes_in_cnt_20")]
        public int? NotesInCnt20 { get; set; }
        [Column("notes_in_cnt_50")]
        public int? NotesInCnt50 { get; set; }
        [Column("notes_in_cnt_100")]
        public int? NotesInCnt100 { get; set; }
        [Column("spare_1")]
        public int? Spare1 { get; set; }
        [Column("spare_2")]
        public int? Spare2 { get; set; }
        [Column("spare_3")]
        public int? Spare3 { get; set; }
        [Column("logged_datetime", TypeName = "datetime")]
        public DateTime? LoggedDatetime { get; set; }
        [Column("comments")]
        [StringLength(255)]
        public string Comments { get; set; }
        [Column("user_id")]
        [StringLength(10)]
        public string UserId { get; set; }
    }
}