// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("patron_preference")]
    public partial class PatronPreference
    {
        [Key]
        [Column("patron_id", TypeName = "numeric(18, 0)")]
        public decimal PatronId { get; set; }
        [Key]
        [Column("preference_group_id")]
        public int PreferenceGroupId { get; set; }
        [Key]
        [Column("patron_preference_type_id")]
        public int PatronPreferenceTypeId { get; set; }
        [Column("system_id")]
        public byte SystemId { get; set; }
        [Column("css_site_id")]
        public short CssSiteId { get; set; }
    }
}