// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("patron")]
    [Index(nameof(CreationCssSiteId), nameof(ExpiryDatetime), Name = "ind_css_site_expiry_dt")]
    [Index(nameof(CreationCssSiteId), Name = "ind_patron_css_site")]
    [Index(nameof(CreationCssSiteId), nameof(Status), nameof(DateOfBirth), Name = "ind_patron_css_site_dob")]
    [Index(nameof(JurisdictionId), Name = "ind_patron_jurisdiction")]
    [Index(nameof(LastName), Name = "ind_patron_last_name")]
    [Index(nameof(LastSessionDatetime), Name = "ind_patron_last_session_dt")]
    [Index(nameof(MembershipId), Name = "ind_patron_member_no")]
    [Index(nameof(Locality), Name = "ind_patron_post_locality")]
    [Index(nameof(ResLocality), Name = "ind_patron_res_locality")]
    [Index(nameof(Status), Name = "ind_patron_status")]
    public partial class Patron
    {
        [Key]
        [Column("id", TypeName = "numeric(18, 0)")]
        public decimal Id { get; set; }
        [Column("creation_system_id")]
        public byte CreationSystemId { get; set; }
        [Column("creation_css_site_id")]
        public short CreationCssSiteId { get; set; }
        [Column("first_name")]
        [StringLength(40)]
        public string FirstName { get; set; }
        [Column("middle_initial")]
        [StringLength(10)]
        public string MiddleInitial { get; set; }
        [Column("last_name")]
        [StringLength(30)]
        public string LastName { get; set; }
        [Column("other_name")]
        [StringLength(30)]
        public string OtherName { get; set; }
        [Column("name_title")]
        [StringLength(15)]
        public string NameTitle { get; set; }
        [Column("res_address_1")]
        [StringLength(60)]
        public string ResAddress1 { get; set; }
        [Column("res_address_2")]
        [StringLength(60)]
        public string ResAddress2 { get; set; }
        [Column("res_locality")]
        [StringLength(30)]
        public string ResLocality { get; set; }
        [Column("res_state_province")]
        [StringLength(30)]
        public string ResStateProvince { get; set; }
        [Column("res_country")]
        [StringLength(30)]
        public string ResCountry { get; set; }
        [Column("res_postal_code")]
        [StringLength(30)]
        public string ResPostalCode { get; set; }
        [Column("postal_address_1")]
        [StringLength(60)]
        public string PostalAddress1 { get; set; }
        [Column("postal_address_2")]
        [StringLength(60)]
        public string PostalAddress2 { get; set; }
        [Column("locality")]
        [StringLength(30)]
        public string Locality { get; set; }
        [Column("state_province")]
        [StringLength(30)]
        public string StateProvince { get; set; }
        [Column("country")]
        [StringLength(30)]
        public string Country { get; set; }
        [Column("postal_code")]
        [StringLength(10)]
        public string PostalCode { get; set; }
        [Column("home_telephone")]
        [StringLength(20)]
        public string HomeTelephone { get; set; }
        [Column("work_telephone")]
        [StringLength(20)]
        public string WorkTelephone { get; set; }
        [Column("fax")]
        [StringLength(20)]
        public string Fax { get; set; }
        [Column("mobile")]
        [StringLength(20)]
        public string Mobile { get; set; }
        [Column("email")]
        [StringLength(255)]
        public string Email { get; set; }
        [Column("next_of_kin")]
        [StringLength(40)]
        public string NextOfKin { get; set; }
        [Column("next_of_kin_telephone")]
        [StringLength(20)]
        public string NextOfKinTelephone { get; set; }
        [Column("date_of_birth", TypeName = "datetime")]
        public DateTime? DateOfBirth { get; set; }
        [Column("sex")]
        [StringLength(1)]
        public string Sex { get; set; }
        [Column("status")]
        [StringLength(10)]
        public string Status { get; set; }
        [Column("creation_datetime", TypeName = "datetime")]
        public DateTime? CreationDatetime { get; set; }
        [Column("expiry_datetime", TypeName = "datetime")]
        public DateTime? ExpiryDatetime { get; set; }
        [Column("suspend_start_datetime", TypeName = "datetime")]
        public DateTime? SuspendStartDatetime { get; set; }
        [Column("suspend_end_datetime", TypeName = "datetime")]
        public DateTime? SuspendEndDatetime { get; set; }
        [Column("membership_id")]
        public int? MembershipId { get; set; }
        [Column("membership_type_id")]
        public int? MembershipTypeId { get; set; }
        [Column("last_session_datetime", TypeName = "datetime")]
        public DateTime? LastSessionDatetime { get; set; }
        [Column("last_modified_datetime", TypeName = "datetime")]
        public DateTime? LastModifiedDatetime { get; set; }
        [Column("rating_grade_id")]
        public int? RatingGradeId { get; set; }
        [Column("jurisdiction_id")]
        public int? JurisdictionId { get; set; }
        [Column("mail_out_flag")]
        [StringLength(1)]
        public string MailOutFlag { get; set; }
    }
}