// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("patron_identification")]
    public partial class PatronIdentification
    {
        [Key]
        [Column("id", TypeName = "numeric(18, 0)")]
        public decimal Id { get; set; }
        [Column("patron_id", TypeName = "numeric(18, 0)")]
        public decimal PatronId { get; set; }
        [Column("identification_item_id")]
        public int IdentificationItemId { get; set; }
        [Column("reference_datetime", TypeName = "datetime")]
        public DateTime? ReferenceDatetime { get; set; }
        [Column("point_value")]
        public short? PointValue { get; set; }
        [Column("image_file_location")]
        [StringLength(255)]
        public string ImageFileLocation { get; set; }
        [Column("location_css_site_id")]
        public short? LocationCssSiteId { get; set; }
        [Column("detail_1")]
        [StringLength(255)]
        public string Detail1 { get; set; }
        [Column("detail_2")]
        [StringLength(255)]
        public string Detail2 { get; set; }
    }
}