// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("patron_banking")]
    public partial class PatronBanking
    {
        [Key]
        [Column("id", TypeName = "numeric(18, 0)")]
        public decimal Id { get; set; }
        [Column("patron_id", TypeName = "numeric(18, 0)")]
        public decimal PatronId { get; set; }
        [Required]
        [Column("banking_type")]
        [StringLength(8)]
        public string BankingType { get; set; }
        [Column("sub_banking_type")]
        [StringLength(20)]
        public string SubBankingType { get; set; }
        [Column("expiry_datetime", TypeName = "datetime")]
        public DateTime? ExpiryDatetime { get; set; }
        [Column("detail_1")]
        [StringLength(64)]
        public string Detail1 { get; set; }
        [Column("detail_2")]
        [StringLength(64)]
        public string Detail2 { get; set; }
        [Column("detail_3")]
        [StringLength(150)]
        public string Detail3 { get; set; }
        [Column("priority")]
        public short? Priority { get; set; }
        [Column("detail_4")]
        [StringLength(64)]
        public string Detail4 { get; set; }
        [Column("detail_5")]
        [StringLength(20)]
        public string Detail5 { get; set; }
        [Column("detail_6")]
        [StringLength(100)]
        public string Detail6 { get; set; }
    }
}