// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("patron_contact")]
    public partial class PatronContact
    {
        [Key]
        [Column("patron_id", TypeName = "numeric(18, 0)")]
        public decimal PatronId { get; set; }
        [Key]
        [Column("contact_type_id")]
        public short ContactTypeId { get; set; }
        [Column("points_awarded_flag")]
        [StringLength(1)]
        public string PointsAwardedFlag { get; set; }
        [Column("last_contact_request_datetime", TypeName = "datetime")]
        public DateTime? LastContactRequestDatetime { get; set; }
        [Column("subscribed_flag")]
        [StringLength(1)]
        public string SubscribedFlag { get; set; }
    }
}