// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("patron_contact_history")]
    public partial class PatronContactHistory
    {
        [Key]
        [Column("patron_id", TypeName = "numeric(18, 0)")]
        public decimal PatronId { get; set; }
        [Key]
        [Column("contact_type_id")]
        public short ContactTypeId { get; set; }
        [Key]
        [Column("contact_details")]
        [StringLength(255)]
        public string ContactDetails { get; set; }
        [Column("bounced_flag")]
        [StringLength(1)]
        public string BouncedFlag { get; set; }
        [Column("notified_kiosk_flag")]
        [StringLength(1)]
        public string NotifiedKioskFlag { get; set; }
    }
}