// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("patron_group")]
    [Index(nameof(Status), Name = "ind_patron_group_status")]
    public partial class PatronGroup
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("system_id")]
        public byte SystemId { get; set; }
        [Column("css_site_id")]
        public short CssSiteId { get; set; }
        [Column("description")]
        [StringLength(30)]
        public string Description { get; set; }
        [Column("type")]
        [StringLength(10)]
        public string Type { get; set; }
        [Column("status")]
        [StringLength(10)]
        public string Status { get; set; }
        [Column("creation_datetime", TypeName = "datetime")]
        public DateTime? CreationDatetime { get; set; }
        [Column("expiry_datetime", TypeName = "datetime")]
        public DateTime? ExpiryDatetime { get; set; }
        [Column("suspend_start_datetime", TypeName = "datetime")]
        public DateTime? SuspendStartDatetime { get; set; }
        [Column("suspend_end_datetime", TypeName = "datetime")]
        public DateTime? SuspendEndDatetime { get; set; }
        [Column("tour_start_datetime", TypeName = "datetime")]
        public DateTime? TourStartDatetime { get; set; }
        [Column("tour_end_datetime", TypeName = "datetime")]
        public DateTime? TourEndDatetime { get; set; }
    }
}