// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("patron_account")]
    [Index(nameof(AccountId), Name = "ind_patron_acc_acc")]
    public partial class PatronAccount
    {
        [Key]
        [Column("patron_id", TypeName = "numeric(18, 0)")]
        public decimal PatronId { get; set; }
        [Key]
        [Column("account_id", TypeName = "numeric(18, 0)")]
        public decimal AccountId { get; set; }
    }
}