// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("patron_last_activity")]
    public partial class PatronLastActivity
    {
        [Key]
        [Column("patron_id", TypeName = "numeric(18, 0)")]
        public decimal PatronId { get; set; }
        [Column("last_kiosk_activity", TypeName = "datetime")]
        public DateTime? LastKioskActivity { get; set; }
        [Column("last_egm_activity", TypeName = "datetime")]
        public DateTime? LastEgmActivity { get; set; }
        [Column("last_pos_activity", TypeName = "datetime")]
        public DateTime? LastPosActivity { get; set; }
        [Column("last_barrel_draw_ticket", TypeName = "datetime")]
        public DateTime? LastBarrelDrawTicket { get; set; }
    }
}