// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("patron_account_permission")]
    public partial class PatronAccountPermission
    {
        [Key]
        [Column("account_id", TypeName = "numeric(18, 0)")]
        public decimal AccountId { get; set; }
        [Key]
        [Column("patron_id", TypeName = "numeric(18, 0)")]
        public decimal PatronId { get; set; }
        [Key]
        [Column("account_permission_type_id")]
        public short AccountPermissionTypeId { get; set; }
    }
}