// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("patron_extra")]
    public partial class PatronExtra
    {
        [Key]
        [Column("patron_id", TypeName = "numeric(18, 0)")]
        public decimal PatronId { get; set; }
        [Key]
        [Column("patron_extra_type_id", TypeName = "numeric(18, 0)")]
        public decimal PatronExtraTypeId { get; set; }
        [Column("detail_value")]
        [StringLength(255)]
        public string DetailValue { get; set; }
    }
}