// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("player_exclusion_transaction")]
    [Index(nameof(SiteId), nameof(PatronId), nameof(TransactionTypeId), nameof(TransactionDatetime), Name = "index_pl_excl_tran")]
    public partial class PlayerExclusionTransaction
    {
        [Key]
        [Column("transaction_id", TypeName = "numeric(18, 0)")]
        public decimal TransactionId { get; set; }
        [Column("site_id")]
        public short SiteId { get; set; }
        [Column("patron_id", TypeName = "numeric(18, 0)")]
        public decimal PatronId { get; set; }
        [Column("transaction_type_id")]
        public short? TransactionTypeId { get; set; }
        [Column("transaction_datetime", TypeName = "datetime")]
        public DateTime TransactionDatetime { get; set; }
        [Column("user_id")]
        [StringLength(16)]
        public string UserId { get; set; }
        [Column("comment_1")]
        [StringLength(255)]
        public string Comment1 { get; set; }
        [Column("comment_2")]
        [StringLength(255)]
        public string Comment2 { get; set; }
        [Column("exclusion_type_id")]
        public short? ExclusionTypeId { get; set; }
    }
}