// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("player_exclusion_type")]
    public partial class PlayerExclusionType
    {
        [Key]
        [Column("exclusion_type_id")]
        public short ExclusionTypeId { get; set; }
        [Required]
        [Column("exclusion_description")]
        [StringLength(255)]
        public string ExclusionDescription { get; set; }
        [Required]
        [Column("venue_description")]
        [StringLength(50)]
        public string VenueDescription { get; set; }
        [Column("report_description")]
        [StringLength(50)]
        public string ReportDescription { get; set; }
    }
}