// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("player_choice_statistics")]
    public partial class PlayerChoiceStatistics
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("manufacturer_id")]
        public short ManufacturerId { get; set; }
        [Key]
        [Column("ssan")]
        public int Ssan { get; set; }
        [Key]
        [Column("game_version_number")]
        public int GameVersionNumber { get; set; }
        [Key]
        [Column("start_datetime", TypeName = "datetime")]
        public DateTime StartDatetime { get; set; }
        [Column("number_of_elements")]
        public int? NumberOfElements { get; set; }
        [Column("element_size")]
        public int? ElementSize { get; set; }
        [Column("player_choices_array")]
        [StringLength(160)]
        public string PlayerChoicesArray { get; set; }
    }
}