// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("player_exclusion_host_audit")]
    public partial class PlayerExclusionHostAudit
    {
        [Key]
        [Column("transaction_id", TypeName = "numeric(18, 0)")]
        public decimal TransactionId { get; set; }
        [Column("site_id")]
        public short SiteId { get; set; }
        [Column("patron_id", TypeName = "numeric(18, 0)")]
        public decimal PatronId { get; set; }
        [Column("transaction_type_id")]
        public short TransactionTypeId { get; set; }
        [Column("exclusion_type_id")]
        [StringLength(30)]
        public string ExclusionTypeId { get; set; }
        [Column("transaction_datetime", TypeName = "datetime")]
        public DateTime TransactionDatetime { get; set; }
        [Required]
        [Column("user_id")]
        [StringLength(16)]
        public string UserId { get; set; }
        [Column("comment_1")]
        [StringLength(255)]
        public string Comment1 { get; set; }
        [Column("comment_2")]
        [StringLength(255)]
        public string Comment2 { get; set; }
        [Required]
        [Column("transaction_change_type")]
        [StringLength(15)]
        public string TransactionChangeType { get; set; }
        [Key]
        [Column("audit_datetime", TypeName = "datetime")]
        public DateTime AuditDatetime { get; set; }
        [Required]
        [Column("host_user_id")]
        [StringLength(16)]
        public string HostUserId { get; set; }
        [Column("new_exclusion_type_id")]
        [StringLength(30)]
        public string NewExclusionTypeId { get; set; }
        [Column("new_comment_1")]
        [StringLength(255)]
        public string NewComment1 { get; set; }
        [Column("new_comment_2")]
        [StringLength(255)]
        public string NewComment2 { get; set; }
    }
}