// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("points_play_configuration")]
    public partial class PointsPlayConfiguration
    {
        public PointsPlayConfiguration()
        {
            PointsPlayDenomination = new HashSet<PointsPlayDenomination>();
            PointsPlayRatingGrade = new HashSet<PointsPlayRatingGrade>();
            PointsPlayTrackingType = new HashSet<PointsPlayTrackingType>();
        }

        [Key]
        [Column("id", TypeName = "numeric(18, 0)")]
        public decimal Id { get; set; }
        [Column("css_site_id")]
        public short CssSiteId { get; set; }
        [Required]
        [Column("enabled_flag")]
        [StringLength(1)]
        public string EnabledFlag { get; set; }
        [Required]
        [Column("description")]
        [StringLength(30)]
        public string Description { get; set; }
        [Column("creation_datetime", TypeName = "datetime")]
        public DateTime CreationDatetime { get; set; }

        [InverseProperty("PointsPlayConfiguration")]
        public virtual ICollection<PointsPlayDenomination> PointsPlayDenomination { get; set; }
        [InverseProperty("PointsPlayConfiguration")]
        public virtual ICollection<PointsPlayRatingGrade> PointsPlayRatingGrade { get; set; }
        [InverseProperty("PointsPlayConfiguration")]
        public virtual ICollection<PointsPlayTrackingType> PointsPlayTrackingType { get; set; }
    }
}