// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("point_purge_timeframe")]
    public partial class PointPurgeTimeframe
    {
        [Key]
        [Column("id")]
        public short Id { get; set; }
        [Required]
        [Column("description")]
        [StringLength(40)]
        public string Description { get; set; }
    }
}