// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("point_purge_audit")]
    public partial class PointPurgeAudit
    {
        [Column("css_site_id")]
        public short CssSiteId { get; set; }
        [Key]
        [Column("id", TypeName = "numeric(18, 0)")]
        public decimal Id { get; set; }
        [Column("point_purge_configuration_id", TypeName = "numeric(18, 0)")]
        public decimal PointPurgeConfigurationId { get; set; }
        [Column("audit_datetime", TypeName = "datetime")]
        public DateTime? AuditDatetime { get; set; }
        [Column("user_id")]
        [StringLength(10)]
        public string UserId { get; set; }
        [Column("func")]
        [StringLength(50)]
        public string Func { get; set; }
        [Column("parameters")]
        [StringLength(255)]
        public string Parameters { get; set; }
    }
}