// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("point_purge_date_criterion")]
    public partial class PointPurgeDateCriterion
    {
        [Column("css_site_id")]
        public short CssSiteId { get; set; }
        [Key]
        [Column("id", TypeName = "numeric(18, 0)")]
        public decimal Id { get; set; }
        [Column("point_purge_configuration_id", TypeName = "numeric(18, 0)")]
        public decimal PointPurgeConfigurationId { get; set; }
        [Column("configuration_datetime", TypeName = "datetime")]
        public DateTime? ConfigurationDatetime { get; set; }
        [Column("configuration_string")]
        [StringLength(20)]
        public string ConfigurationString { get; set; }
        [Column("configuration_number")]
        public byte? ConfigurationNumber { get; set; }
    }
}