// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("points_play_denomination")]
    public partial class PointsPlayDenomination
    {
        [Key]
        [Column("points_play_configuration_id", TypeName = "numeric(18, 0)")]
        public decimal PointsPlayConfigurationId { get; set; }
        [Key]
        [Column("css_site_id")]
        public short CssSiteId { get; set; }
        [Key]
        [Column("drawdown_denomination_id", TypeName = "numeric(18, 0)")]
        public decimal DrawdownDenominationId { get; set; }

        [ForeignKey(nameof(CssSiteId))]
        [InverseProperty("PointsPlayDenomination")]
        public virtual CssSite CssSite { get; set; }
        [ForeignKey(nameof(DrawdownDenominationId))]
        [InverseProperty("PointsPlayDenomination")]
        public virtual DrawdownDenomination DrawdownDenomination { get; set; }
        [ForeignKey(nameof(PointsPlayConfigurationId))]
        [InverseProperty("PointsPlayDenomination")]
        public virtual PointsPlayConfiguration PointsPlayConfiguration { get; set; }
    }
}