// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("point_purge_configuration")]
    public partial class PointPurgeConfiguration
    {
        [Column("css_site_id")]
        public short CssSiteId { get; set; }
        [Key]
        [Column("id", TypeName = "numeric(18, 0)")]
        public decimal Id { get; set; }
        [Required]
        [Column("enabled_flag")]
        [StringLength(1)]
        public string EnabledFlag { get; set; }
        [Column("tracking_type_id")]
        public short TrackingTypeId { get; set; }
        [Column("point_purge_timeframe_id")]
        public short PointPurgeTimeframeId { get; set; }
    }
}