// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("points_play_tracking_type")]
    public partial class PointsPlayTrackingType
    {
        [Key]
        [Column("points_play_configuration_id", TypeName = "numeric(18, 0)")]
        public decimal PointsPlayConfigurationId { get; set; }
        [Key]
        [Column("css_site_id")]
        public short CssSiteId { get; set; }
        [Key]
        [Column("tracking_type_id")]
        public byte TrackingTypeId { get; set; }

        [ForeignKey(nameof(PointsPlayConfigurationId))]
        [InverseProperty("PointsPlayTrackingType")]
        public virtual PointsPlayConfiguration PointsPlayConfiguration { get; set; }
    }
}