// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("port_configuration")]
    public partial class PortConfiguration
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("host_serial_number")]
        public int HostSerialNumber { get; set; }
        [Key]
        [Column("port")]
        public short Port { get; set; }
        [Column("loop_name")]
        [StringLength(8)]
        public string LoopName { get; set; }
        [Column("weighting")]
        public short? Weighting { get; set; }
        [Key]
        [Column("remote_port")]
        [StringLength(30)]
        public string RemotePort { get; set; }
    }
}