// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("pos_transaction_tax")]
    [Index(nameof(SiteId), nameof(CssSiteId), nameof(SalesId), Name = "ind_pos_transaction_tax_css_site_id_sale_id")]
    public partial class PosTransactionTax
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("css_site_id")]
        public short CssSiteId { get; set; }
        [Key]
        [Column("sales_id")]
        [StringLength(15)]
        public string SalesId { get; set; }
        [Key]
        [Column("tax_code")]
        [StringLength(20)]
        public string TaxCode { get; set; }
        [Column("tax_description")]
        [StringLength(30)]
        public string TaxDescription { get; set; }
        [Column("amount")]
        public int? Amount { get; set; }

        [ForeignKey("SiteId,CssSiteId,SalesId")]
        [InverseProperty("PosTransactionTax")]
        public virtual PosTransactionSale PosTransactionSale { get; set; }
    }
}