// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("pos_transaction_payment")]
    [Index(nameof(SiteId), nameof(CssSiteId), nameof(SalesId), Name = "ind_pos_transaction_payment_css_site_id_sale_id")]
    public partial class PosTransactionPayment
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("css_site_id")]
        public short CssSiteId { get; set; }
        [Key]
        [Column("sales_id")]
        [StringLength(15)]
        public string SalesId { get; set; }
        [Key]
        [Column("payment_code")]
        [StringLength(20)]
        public string PaymentCode { get; set; }
        [Column("payment_description")]
        [StringLength(30)]
        public string PaymentDescription { get; set; }
        [Column("is_points_payment")]
        public bool? IsPointsPayment { get; set; }
        [Column("is_cash_purchase_payment")]
        public bool? IsCashPurchasePayment { get; set; }
        [Column("tendered_amount")]
        public int? TenderedAmount { get; set; }
        [Column("change_amount")]
        public int? ChangeAmount { get; set; }

        [ForeignKey("SiteId,CssSiteId,SalesId")]
        [InverseProperty("PosTransactionPayment")]
        public virtual PosTransactionSale PosTransactionSale { get; set; }
    }
}