// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("pos_transaction_sale")]
    [Index(nameof(PatronId), nameof(SaleDate), Name = "ind_patron_id_sale_date")]
    public partial class PosTransactionSale
    {
        public PosTransactionSale()
        {
            PosTransactionItem = new HashSet<PosTransactionItem>();
            PosTransactionPayment = new HashSet<PosTransactionPayment>();
            PosTransactionTax = new HashSet<PosTransactionTax>();
        }

        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("css_site_id")]
        public short CssSiteId { get; set; }
        [Key]
        [Column("sales_id")]
        [StringLength(15)]
        public string SalesId { get; set; }
        [Column("terminal_id")]
        [StringLength(15)]
        public string TerminalId { get; set; }
        [Column("terminal_name")]
        [StringLength(20)]
        public string TerminalName { get; set; }
        [Column("location_id")]
        [StringLength(15)]
        public string LocationId { get; set; }
        [Column("location_name")]
        [StringLength(20)]
        public string LocationName { get; set; }
        [Column("card_id")]
        public int? CardId { get; set; }
        [Column("sale_date", TypeName = "datetime")]
        public DateTime? SaleDate { get; set; }
        [Column("sale_total")]
        public int? SaleTotal { get; set; }
        [Column("patron_id", TypeName = "numeric(18, 0)")]
        public decimal? PatronId { get; set; }

        [InverseProperty("PosTransactionSale")]
        public virtual ICollection<PosTransactionItem> PosTransactionItem { get; set; }
        [InverseProperty("PosTransactionSale")]
        public virtual ICollection<PosTransactionPayment> PosTransactionPayment { get; set; }
        [InverseProperty("PosTransactionSale")]
        public virtual ICollection<PosTransactionTax> PosTransactionTax { get; set; }
    }
}