// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("pos_transaction_item")]
    [Index(nameof(SiteId), nameof(CssSiteId), nameof(SalesId), Name = "ind_pos_transaction_item_css_site_id_sale_id")]
    public partial class PosTransactionItem
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("css_site_id")]
        public short CssSiteId { get; set; }
        [Key]
        [Column("sales_id")]
        [StringLength(15)]
        public string SalesId { get; set; }
        [Key]
        [Column("item_code")]
        [StringLength(20)]
        public string ItemCode { get; set; }
        [Column("item_description")]
        [StringLength(30)]
        public string ItemDescription { get; set; }
        [Column("category_code")]
        [StringLength(10)]
        public string CategoryCode { get; set; }
        [Column("category_description")]
        [StringLength(30)]
        public string CategoryDescription { get; set; }
        [Column("unit_price")]
        public int? UnitPrice { get; set; }
        [Column("cost_price")]
        public int? CostPrice { get; set; }
        [Column("qty")]
        public int? Qty { get; set; }
        [Column("sale_value")]
        public int? SaleValue { get; set; }

        [ForeignKey("SiteId,CssSiteId,SalesId")]
        [InverseProperty("PosTransactionItem")]
        public virtual PosTransactionSale PosTransactionSale { get; set; }
    }
}