// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("prize_draw")]
    public partial class PrizeDraw
    {
        [Key]
        [Column("id", TypeName = "numeric(18, 0)")]
        public decimal Id { get; set; }
        [Key]
        [Column("css_site_id")]
        public short CssSiteId { get; set; }
        [Required]
        [Column("prize_description")]
        [StringLength(100)]
        public string PrizeDescription { get; set; }
        [Column("enabled")]
        [StringLength(1)]
        public string Enabled { get; set; }
        [Column("prize_type")]
        [StringLength(8)]
        public string PrizeType { get; set; }
        [Column("probability")]
        public int? Probability { get; set; }
        [Column("prize_draw_starts", TypeName = "datetime")]
        public DateTime? PrizeDrawStarts { get; set; }
        [Column("prize_draw_ends", TypeName = "datetime")]
        public DateTime? PrizeDrawEnds { get; set; }
        [Column("day_of_week")]
        [StringLength(3)]
        public string DayOfWeek { get; set; }
        [Column("month_of_year")]
        [StringLength(3)]
        public string MonthOfYear { get; set; }
        [Column("prize_value")]
        public int? PrizeValue { get; set; }
        [Column("points_value")]
        public int? PointsValue { get; set; }
        [Column("points_type")]
        public int? PointsType { get; set; }
        [Column("you_have_won")]
        [StringLength(100)]
        public string YouHaveWon { get; set; }
        [Column("days_to_expiry")]
        public int? DaysToExpiry { get; set; }
        [Column("ticket_text")]
        [StringLength(100)]
        public string TicketText { get; set; }
        [Column("rating_grade_id")]
        public int? RatingGradeId { get; set; }
        [Column("birthday_prize_criteria_type")]
        [StringLength(1)]
        public string BirthdayPrizeCriteriaType { get; set; }
        [Column("birthday_prize_days_span")]
        public int? BirthdayPrizeDaysSpan { get; set; }
        [Column("prize_quantity")]
        public int? PrizeQuantity { get; set; }
        [Column("simplay_trigger_prize")]
        [StringLength(1)]
        public string SimplayTriggerPrize { get; set; }
        [Column("second_chance_draw", TypeName = "datetime")]
        public DateTime? SecondChanceDraw { get; set; }
        [Column("rating_grade_list")]
        [StringLength(100)]
        public string RatingGradeList { get; set; }
        [Column("print_expiry_date_flag")]
        [StringLength(1)]
        public string PrintExpiryDateFlag { get; set; }
        [Column("prize_does_not_expire_flag")]
        [StringLength(1)]
        public string PrizeDoesNotExpireFlag { get; set; }
        [Column("prize_expires_end_of_month_flag")]
        [StringLength(1)]
        public string PrizeExpiresEndOfMonthFlag { get; set; }
        [Column("prize_expiry_datetime", TypeName = "datetime")]
        public DateTime? PrizeExpiryDatetime { get; set; }
        [Column("sex")]
        [StringLength(1)]
        public string Sex { get; set; }
    }
}