// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Keyless]
    [Table("qogr_egm_signatures")]
    [Index(nameof(SoftwareSetApprovalNumber), nameof(SignatureDate), Name = "UQ__qogr_egm_signatu__61FB72FB", IsUnique = true)]
    [Index(nameof(SoftwareSetApprovalNumber), Name = "ind_ssan")]
    public partial class QogrEgmSignatures
    {
        [Required]
        [Column("software_set_approval_number")]
        [StringLength(10)]
        public string SoftwareSetApprovalNumber { get; set; }
        [Column("software_component_id")]
        [StringLength(10)]
        public string SoftwareComponentId { get; set; }
        [Column("manufacturer_id")]
        public short? ManufacturerId { get; set; }
        [Column("software_set_name")]
        [StringLength(80)]
        public string SoftwareSetName { get; set; }
        [Column("signature_date", TypeName = "datetime")]
        public DateTime SignatureDate { get; set; }
        [Column("signature")]
        [StringLength(64)]
        public string Signature { get; set; }
    }
}