// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Keyless]
    [Table("qogr_ducms_config")]
    [Index(nameof(Mid), nameof(Egm), Name = "mid_egm", IsUnique = true)]
    public partial class QogrDucmsConfig
    {
        [Column("id", TypeName = "numeric(18, 0)")]
        public decimal Id { get; set; }
        [Column("mid")]
        [StringLength(2)]
        public string Mid { get; set; }
        [Column("egm")]
        [StringLength(6)]
        public string Egm { get; set; }
        [Column("hardware_number")]
        [StringLength(10)]
        public string HardwareNumber { get; set; }
        [Column("software_number")]
        [StringLength(10)]
        public string SoftwareNumber { get; set; }
        [Column("cabinet_type")]
        [StringLength(1)]
        public string CabinetType { get; set; }
        [Column("prog_control")]
        [StringLength(1)]
        public string ProgControl { get; set; }
        [Column("touch_screen")]
        [StringLength(1)]
        public string TouchScreen { get; set; }
        [Column("ticket_printer")]
        [StringLength(1)]
        public string TicketPrinter { get; set; }
        [Column("coin_token")]
        [StringLength(1)]
        public string CoinToken { get; set; }
        [Column("hopper")]
        [StringLength(1)]
        public string Hopper { get; set; }
        [Column("note_acceptor")]
        [StringLength(1)]
        public string NoteAcceptor { get; set; }
        [Column("denomination")]
        [StringLength(4)]
        public string Denomination { get; set; }
        [Column("token")]
        [StringLength(4)]
        public string Token { get; set; }
        [Column("site")]
        [StringLength(10)]
        public string Site { get; set; }
        [Column("lcom")]
        [StringLength(5)]
        public string Lcom { get; set; }
        [Column("poll_add")]
        [StringLength(3)]
        public string PollAdd { get; set; }
        [Column("owner")]
        [StringLength(3)]
        public string Owner { get; set; }
    }
}