// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Keyless]
    [Table("qogr_software_deno")]
    [Index(nameof(Id), Name = "software_deno_id", IsUnique = true)]
    public partial class QogrSoftwareDeno
    {
        [Column("id", TypeName = "numeric(5, 0)")]
        public decimal Id { get; set; }
        [Column("mid")]
        [StringLength(2)]
        public string Mid { get; set; }
        [Column("software_approval_number")]
        [StringLength(10)]
        public string SoftwareApprovalNumber { get; set; }
        [Column("denomination")]
        [StringLength(4)]
        public string Denomination { get; set; }
        [Column("token")]
        [StringLength(4)]
        public string Token { get; set; }
    }
}