// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("qogr_approved_technician")]
    public partial class QogrApprovedTechnician
    {
        [Key]
        [Column("name")]
        [StringLength(30)]
        public string Name { get; set; }
        [Key]
        [Column("licence_number")]
        [StringLength(15)]
        public string LicenceNumber { get; set; }
    }
}