// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Keyless]
    [Table("qogr_software_list")]
    [Index(nameof(SoftwareApprovalNumber), Name = "ind_software_approval_number")]
    [Index(nameof(Id), Name = "software_id", IsUnique = true)]
    public partial class QogrSoftwareList
    {
        [Column("id", TypeName = "numeric(5, 0)")]
        public decimal Id { get; set; }
        [Column("mid")]
        [StringLength(2)]
        public string Mid { get; set; }
        [Column("software_set_name")]
        [StringLength(30)]
        public string SoftwareSetName { get; set; }
        [Column("software_identifier_number")]
        [StringLength(10)]
        public string SoftwareIdentifierNumber { get; set; }
        [Column("software_approval_number")]
        [StringLength(10)]
        public string SoftwareApprovalNumber { get; set; }
        [Column("protocol_version")]
        [StringLength(2)]
        public string ProtocolVersion { get; set; }
        [Column("approval_status")]
        [StringLength(3)]
        public string ApprovalStatus { get; set; }
        [Column("manufacturer_version_id")]
        [StringLength(15)]
        public string ManufacturerVersionId { get; set; }
    }
}