// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Keyless]
    [Table("qogr_approved_egm_jackpots")]
    public partial class QogrApprovedEgmJackpots
    {
        [Column("manufacturer_id")]
        public short ManufacturerId { get; set; }
        [Required]
        [Column("software_set_approval_number")]
        [StringLength(10)]
        public string SoftwareSetApprovalNumber { get; set; }
        [Column("software_component_id")]
        public int SoftwareComponentId { get; set; }
        [Column("jackpot_approval_number")]
        public int JackpotApprovalNumber { get; set; }
    }
}