// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("qogr_egm_software_set")]
    public partial class QogrEgmSoftwareSet
    {
        [Key]
        [Column("ssan")]
        public int Ssan { get; set; }
        [Column("software_component_id")]
        public int SoftwareComponentId { get; set; }
        [Column("manufacturer_id")]
        public short ManufacturerId { get; set; }
        [Required]
        [Column("software_set_name")]
        [StringLength(80)]
        public string SoftwareSetName { get; set; }
    }
}