// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Keyless]
    [Table("qogr_hardware_list")]
    [Index(nameof(Id), Name = "hardware_id", IsUnique = true)]
    public partial class QogrHardwareList
    {
        [Column("id", TypeName = "numeric(5, 0)")]
        public decimal Id { get; set; }
        [Column("mid")]
        [StringLength(2)]
        public string Mid { get; set; }
        [Column("hardware_product_name")]
        [StringLength(30)]
        public string HardwareProductName { get; set; }
        [Column("hardware_identifier_number")]
        [StringLength(10)]
        public string HardwareIdentifierNumber { get; set; }
        [Column("hardware_approval_number")]
        [StringLength(10)]
        public string HardwareApprovalNumber { get; set; }
        [Column("approval_status")]
        [StringLength(3)]
        public string ApprovalStatus { get; set; }
    }
}