// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("qogr_egm_seeds")]
    [Index(nameof(SeedDate), Name = "PK_QOGR_EGM_SEEDS", IsUnique = true)]
    public partial class QogrEgmSeeds
    {
        [Key]
        [Column("seed_date", TypeName = "datetime")]
        public DateTime SeedDate { get; set; }
        [Column("seed")]
        [StringLength(64)]
        public string Seed { get; set; }
    }
}