// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("QOGR_report_dates")]
    public partial class QOGRReportDates
    {
        [Key]
        public byte Id { get; set; }
        [Column("YYYY")]
        public int Yyyy { get; set; }
        [Column("MM")]
        public byte Mm { get; set; }
        [Column("DD")]
        public byte? Dd { get; set; }
        [Column(TypeName = "smalldatetime")]
        public DateTime Date { get; set; }
    }
}