// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("qogr_jackpot_approval")]
    public partial class QogrJackpotApproval
    {
        [Key]
        [Column("pool_number")]
        public int PoolNumber { get; set; }
        [Column("approval_number")]
        public int? ApprovalNumber { get; set; }
        [Column("variation_number")]
        public int? VariationNumber { get; set; }
        [Column("set_number")]
        public int? SetNumber { get; set; }
    }
}