// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("qogr_seal_approval")]
    public partial class QogrSealApproval
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("serial_number")]
        public int SerialNumber { get; set; }
        [Key]
        [Column("start_datetime", TypeName = "datetime")]
        public DateTime StartDatetime { get; set; }
        [Column("name")]
        [StringLength(30)]
        public string Name { get; set; }
        [Column("licence_number")]
        [StringLength(15)]
        public string LicenceNumber { get; set; }
        [Column("old_seal_number")]
        [StringLength(15)]
        public string OldSealNumber { get; set; }
        [Column("new_seal_number")]
        [StringLength(15)]
        public string NewSealNumber { get; set; }
        [Column("authority_number")]
        public int AuthorityNumber { get; set; }
        [Column("device_type_id")]
        public short? DeviceTypeId { get; set; }
        [Column("user_id")]
        [StringLength(10)]
        public string UserId { get; set; }
    }
}