// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("random_member_draw")]
    public partial class RandomMemberDraw
    {
        [Key]
        [Column("css_site_id")]
        public short CssSiteId { get; set; }
        [Key]
        [Column("draw_number")]
        public int DrawNumber { get; set; }
        [Column("draw_datetime", TypeName = "datetime")]
        public DateTime DrawDatetime { get; set; }
        [Column("patron_id", TypeName = "numeric(18, 0)")]
        public decimal? PatronId { get; set; }
        [Column("membership_id")]
        public int? MembershipId { get; set; }
        [Column("prize_description")]
        [StringLength(25)]
        public string PrizeDescription { get; set; }
        [Column("claimed")]
        [StringLength(1)]
        public string Claimed { get; set; }
    }
}