// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("redemption_voucher")]
    [Index(nameof(CssSiteId), nameof(ExpiryDatetime), Name = "ind_css_site_expiry_dt")]
    [Index(nameof(CssSiteId), nameof(LastAction), nameof(Status), Name = "ind_last_action_status")]
    [Index(nameof(RedemptionItemId), Name = "ind_redemption_item_id")]
    public partial class RedemptionVoucher
    {
        [Key]
        [Column("id", TypeName = "numeric(18, 0)")]
        public decimal Id { get; set; }
        [Column("system_id")]
        public byte SystemId { get; set; }
        [Key]
        [Column("css_site_id")]
        public short CssSiteId { get; set; }
        [Column("account_id", TypeName = "numeric(18, 0)")]
        public decimal AccountId { get; set; }
        [Column("patron_id", TypeName = "numeric(18, 0)")]
        public decimal PatronId { get; set; }
        [Column("creation_datetime", TypeName = "datetime")]
        public DateTime? CreationDatetime { get; set; }
        [Column("expiry_datetime", TypeName = "datetime")]
        public DateTime? ExpiryDatetime { get; set; }
        [Column("redemption_item_id", TypeName = "numeric(18, 0)")]
        public decimal? RedemptionItemId { get; set; }
        [Column("amount", TypeName = "numeric(18, 0)")]
        public decimal? Amount { get; set; }
        [Column("quantity")]
        public int? Quantity { get; set; }
        [Column("comment_1")]
        [StringLength(60)]
        public string Comment1 { get; set; }
        [Column("comment_2")]
        [StringLength(60)]
        public string Comment2 { get; set; }
        [Column("comment_3")]
        [StringLength(60)]
        public string Comment3 { get; set; }
        [Column("status")]
        [StringLength(10)]
        public string Status { get; set; }
        [Column("last_action", TypeName = "datetime")]
        public DateTime? LastAction { get; set; }
        [Column("user_id")]
        [StringLength(10)]
        public string UserId { get; set; }
        [Column("linked_voucher_number", TypeName = "numeric(18, 0)")]
        public decimal? LinkedVoucherNumber { get; set; }
        [Column("network_device_id", TypeName = "numeric(18, 0)")]
        public decimal? NetworkDeviceId { get; set; }
    }
}