// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("signature_link")]
    public partial class SignatureLink
    {
        [Key]
        [Column("id")]
        public Guid Id { get; set; }
        [Key]
        [Column("signature_id")]
        public Guid SignatureId { get; set; }
        [Column("site_id")]
        public int SiteId { get; set; }
        [Column("creation_datetime", TypeName = "datetime")]
        public DateTime CreationDatetime { get; set; }
    }
}