// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("site_hourly_summary")]
    [Index(nameof(SnapshotDatetime), nameof(SiteId), Name = "ind_snapdate_site")]
    public partial class SiteHourlySummary
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("snapshot_datetime", TypeName = "datetime")]
        public DateTime SnapshotDatetime { get; set; }
        [Column("turnover")]
        public int? Turnover { get; set; }
        [Column("head_count")]
        public int? HeadCount { get; set; }
        [Column("all_wins")]
        public int? AllWins { get; set; }
        [Column("cash_clearance")]
        public int? CashClearance { get; set; }
        [Key]
        [Column("denomination_id")]
        public byte DenominationId { get; set; }
        [Column("stroke")]
        public int? Stroke { get; set; }
    }
}