// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("site_host_configuration")]
    public partial class SiteHostConfiguration
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("host_serial_number")]
        public int HostSerialNumber { get; set; }
        [Column("description")]
        [StringLength(30)]
        public string Description { get; set; }
        [Column("primary_network_address")]
        [StringLength(30)]
        public string PrimaryNetworkAddress { get; set; }
        [Column("secondary_network_address")]
        [StringLength(30)]
        public string SecondaryNetworkAddress { get; set; }
        [Column("master")]
        [StringLength(1)]
        public string Master { get; set; }
        [Column("mate")]
        public int? Mate { get; set; }
    }
}