// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("spend_reward_criterion")]
    public partial class SpendRewardCriterion
    {
        [Key]
        [Column("id", TypeName = "numeric(18, 0)")]
        public decimal Id { get; set; }
        [Column("css_site_id")]
        public short CssSiteId { get; set; }
        [Column("rating_grade_id", TypeName = "numeric(18, 0)")]
        public decimal? RatingGradeId { get; set; }
        [Column("tracking_type_id")]
        public short TrackingTypeId { get; set; }
        [Column("spend_reward_reset_timer_id")]
        public short SpendRewardResetTimerId { get; set; }
        [Column("points_value")]
        public int? PointsValue { get; set; }
        [Column("spend_value")]
        public int? SpendValue { get; set; }
        [Column("repeat_count")]
        public short? RepeatCount { get; set; }
        [Column("enabled_flag")]
        [StringLength(1)]
        public string EnabledFlag { get; set; }
    }
}