// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("state_province")]
    public partial class StateProvince
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("country_id")]
        public int CountryId { get; set; }
        [Column("description")]
        [StringLength(30)]
        public string Description { get; set; }
        [Column("iso_code")]
        [StringLength(10)]
        public string IsoCode { get; set; }
        [Column("phone_prefix")]
        [StringLength(10)]
        public string PhonePrefix { get; set; }
    }
}