// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("sys_site_batch_confirm_type")]
    public partial class SysSiteBatchConfirmType
    {
        [Key]
        [Column("id", TypeName = "numeric(18, 0)")]
        public decimal Id { get; set; }
        [Column("system_id")]
        public byte SystemId { get; set; }
        [Column("css_site_id")]
        public short CssSiteId { get; set; }
        [Column("batch_confirm_type_id")]
        public int BatchConfirmTypeId { get; set; }
    }
}