// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("system_site_tracking_type")]
    public partial class SystemSiteTrackingType
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("system_id")]
        public byte SystemId { get; set; }
        [Column("css_site_id")]
        public short CssSiteId { get; set; }
        [Column("tracking_type_id")]
        public byte? TrackingTypeId { get; set; }
        [Column("display_name")]
        [StringLength(30)]
        public string DisplayName { get; set; }
        [Column("period_type")]
        public byte? PeriodType { get; set; }
        [Column("aging_periods")]
        public short? AgingPeriods { get; set; }
        [Column("first_period_datetime", TypeName = "datetime")]
        public DateTime? FirstPeriodDatetime { get; set; }
        [Column("gemini_display_flag")]
        [StringLength(1)]
        public string GeminiDisplayFlag { get; set; }
        [Column("group_flag")]
        [StringLength(1)]
        public string GroupFlag { get; set; }
        [Column("one_monetary_unit", TypeName = "numeric(18, 0)")]
        public decimal? OneMonetaryUnit { get; set; }
        [Column("kiosk_display_flag")]
        [StringLength(1)]
        public string KioskDisplayFlag { get; set; }
    }
}