// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("system_site")]
    public partial class SystemSite
    {
        [Key]
        [Column("css_site_id")]
        public short CssSiteId { get; set; }
        [Key]
        [Column("system_id")]
        public byte SystemId { get; set; }
        [Column("site_id")]
        public short? SiteId { get; set; }
        [Column("licenced_operator")]
        [StringLength(30)]
        public string LicencedOperator { get; set; }
    }
}