// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("tax_rate")]
    public partial class TaxRate
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("css_game_type_id")]
        public int CssGameTypeId { get; set; }
        [Column("jurisdiction_id")]
        public int? JurisdictionId { get; set; }
        [Column("rate_type")]
        [StringLength(10)]
        public string RateType { get; set; }
        [Column("rate", TypeName = "numeric(10, 3)")]
        public decimal? Rate { get; set; }
    }
}