// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("third_party_terminal_device")]
    public partial class ThirdPartyTerminalDevice
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("terminal_id")]
        [StringLength(81)]
        public string TerminalId { get; set; }
        [Column("network_device_id", TypeName = "numeric(18, 0)")]
        public decimal? NetworkDeviceId { get; set; }
    }
}