// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("tito_ticket_transaction")]
    [Index(nameof(TitoTicketTransactionTypeId), nameof(TransactionDatetime), Name = "ind_ttt_transactiontype_datetime")]
    public partial class TitoTicketTransaction
    {
        [Key]
        [Column("ticket_barcode", TypeName = "numeric(18, 0)")]
        public decimal TicketBarcode { get; set; }
        [Key]
        [Column("transaction_datetime", TypeName = "datetime")]
        public DateTime TransactionDatetime { get; set; }
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("tito_ticket_transaction_type_id")]
        public short TitoTicketTransactionTypeId { get; set; }
        [Column("amount")]
        public int Amount { get; set; }
        [Column("tito_implementation_type_id")]
        public short? TitoImplementationTypeId { get; set; }
        [Column("egm_serial_number")]
        public int? EgmSerialNumber { get; set; }
        [Column("user_id")]
        [StringLength(10)]
        public string UserId { get; set; }
        [Column("network_device_id", TypeName = "numeric(18, 0)")]
        public decimal? NetworkDeviceId { get; set; }
        [Column("ticket_number", TypeName = "numeric(12, 0)")]
        public decimal? TicketNumber { get; set; }
    }
}