// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("token")]
    public partial class Token
    {
        public Token()
        {
            Egm = new HashSet<Egm>();
        }

        [Key]
        [Column("id")]
        public short Id { get; set; }
        [Required]
        [Column("representation")]
        [StringLength(8)]
        public string Representation { get; set; }
        [Column("base_currency_value")]
        public int? BaseCurrencyValue { get; set; }
        [Column("standard_weight")]
        public int? StandardWeight { get; set; }
        [Column("calibrated_weight")]
        public int? CalibratedWeight { get; set; }
        [Column("date_calibrated", TypeName = "datetime")]
        public DateTime? DateCalibrated { get; set; }

        [InverseProperty("Token")]
        public virtual ICollection<Egm> Egm { get; set; }
    }
}