// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("turnover_threshold")]
    [Index(nameof(TurnoverThresholdGroupId), Name = "idx_group_id")]
    public partial class TurnoverThreshold
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("turnover_threshold_group_id")]
        public int? TurnoverThresholdGroupId { get; set; }
        [Column("start_range")]
        public int? StartRange { get; set; }
        [Column("end_range")]
        public int? EndRange { get; set; }
        [Column("rate", TypeName = "numeric(18, 6)")]
        public decimal? Rate { get; set; }
    }
}