// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("VC0_table")]
    public partial class Vc0Table
    {
        [Key]
        [Column(TypeName = "datetime")]
        public DateTime ReportDate { get; set; }
        [Key]
        [Column("MID")]
        public byte Mid { get; set; }
        [Key]
        public int Serial { get; set; }
        [Key]
        [Column("GVN")]
        public int Gvn { get; set; }
        [Key]
        public byte Variation { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ConfigStartDateTime { get; set; }
    }
}