// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("voucher_signature_config")]
    public partial class VoucherSignatureConfig
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("voucher_type_id")]
        public int VoucherTypeId { get; set; }
        [Column("description")]
        [StringLength(30)]
        public string Description { get; set; }
        [Column("min_value")]
        public int? MinValue { get; set; }
        [Column("max_value")]
        public int? MaxValue { get; set; }
    }
}