// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("voucher_signatures")]
    public partial class VoucherSignatures
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("voucher_type_id")]
        public int VoucherTypeId { get; set; }
        [Key]
        [Column("config_id")]
        public int ConfigId { get; set; }
        [Key]
        [Column("row_number")]
        public int RowNumber { get; set; }
        [Key]
        [Column("column_number")]
        public int ColumnNumber { get; set; }
        [Column("signature_label")]
        [StringLength(20)]
        public string SignatureLabel { get; set; }
    }
}