// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("wa_jackpot_pool")]
    public partial class WaJackpotPool
    {
        [Key]
        [Column("site_id")]
        public short SiteId { get; set; }
        [Key]
        [Column("pool_number")]
        public int PoolNumber { get; set; }
        [Required]
        [Column("pool_type")]
        [StringLength(8)]
        public string PoolType { get; set; }
        [Required]
        [Column("pool_name")]
        [StringLength(30)]
        public string PoolName { get; set; }
        [Column("reset")]
        public int Reset { get; set; }
        [Column("maximum_value")]
        public int MaximumValue { get; set; }
        [Column("increment")]
        public float Increment { get; set; }
        [Column("date_created", TypeName = "datetime")]
        public DateTime DateCreated { get; set; }
        [Column("date_retired", TypeName = "datetime")]
        public DateTime? DateRetired { get; set; }
        [Column("current_value")]
        public int? CurrentValue { get; set; }
        [Column("current_value_logged_datetime", TypeName = "datetime")]
        public DateTime? CurrentValueLoggedDatetime { get; set; }
        [Column("last_hit", TypeName = "datetime")]
        public DateTime? LastHit { get; set; }
        [Column("weighted_flag")]
        [StringLength(1)]
        public string WeightedFlag { get; set; }
        [Column("current_fill_value")]
        public int? CurrentFillValue { get; set; }
        [Column("current_overflow")]
        public int? CurrentOverflow { get; set; }
        [Required]
        [Column("allow_prize_sharing")]
        [StringLength(1)]
        public string AllowPrizeSharing { get; set; }
        [Column("update_time")]
        public int? UpdateTime { get; set; }
        [Column("sub_pool_type")]
        [StringLength(8)]
        public string SubPoolType { get; set; }
        [Column("status")]
        [StringLength(1)]
        public string Status { get; set; }
        [Column("max_autopay")]
        public int? MaxAutopay { get; set; }
        [Column("prize_value")]
        public int? PrizeValue { get; set; }
        [Column("total_rtp")]
        public double? TotalRtp { get; set; }
        [Column("auxiliary_rtp")]
        public double? AuxiliaryRtp { get; set; }
        [Column("level_name")]
        [StringLength(16)]
        public string LevelName { get; set; }
    }
}