// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("win_reward_conversion")]
    public partial class WinRewardConversion
    {
        [Key]
        [Column("css_site_id")]
        public short CssSiteId { get; set; }
        [Key]
        [Column("win_reward_criterion_id", TypeName = "numeric(18, 0)")]
        public decimal WinRewardCriterionId { get; set; }
        [Key]
        [Column("rating_grade_id")]
        public int RatingGradeId { get; set; }
        [Key]
        [Column("tracking_type_id")]
        public short TrackingTypeId { get; set; }
        [Column("conversion_rate")]
        public short ConversionRate { get; set; }
    }
}