// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("win_reward_conversion_audit")]
    public partial class WinRewardConversionAudit
    {
        [Key]
        [Column("id", TypeName = "numeric(18, 0)")]
        public decimal Id { get; set; }
        [Column("css_site_id")]
        public short? CssSiteId { get; set; }
        [Column("win_reward_criterion_id", TypeName = "numeric(18, 0)")]
        public decimal? WinRewardCriterionId { get; set; }
        [Column("audit_datetime", TypeName = "datetime")]
        public DateTime? AuditDatetime { get; set; }
        [Column("user_id")]
        [StringLength(10)]
        public string UserId { get; set; }
        [Column("action")]
        [StringLength(1)]
        public string Action { get; set; }
        [Column("rating_grade_id")]
        public int? RatingGradeId { get; set; }
        [Column("tracking_type_id")]
        public short? TrackingTypeId { get; set; }
        [Column("conversion_rate")]
        public short? ConversionRate { get; set; }
    }
}