// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("win_reward_event")]
    public partial class WinRewardEvent
    {
        [Key]
        [Column("win_reward_criterion_id", TypeName = "numeric(18, 0)")]
        public decimal WinRewardCriterionId { get; set; }
        [Key]
        [Column("css_site_id")]
        public short CssSiteId { get; set; }
        [Key]
        [Column("card_id")]
        public int CardId { get; set; }
        [Column("egm_serial_number")]
        public int EgmSerialNumber { get; set; }
        [Key]
        [Column("reward_datetime", TypeName = "datetime")]
        public DateTime RewardDatetime { get; set; }
        [Column("tracking_type_id")]
        public short TrackingTypeId { get; set; }
        [Column("win_value")]
        public int? WinValue { get; set; }
        [Column("actual_win_value")]
        public int? ActualWinValue { get; set; }
    }
}