// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Tables
{
    [Table("working_set")]
    public partial class WorkingSet
    {
        [Key]
        [Column("working_set_name")]
        [StringLength(30)]
        public string WorkingSetName { get; set; }
        [Key]
        [Column("working_set_type")]
        [StringLength(10)]
        public string WorkingSetType { get; set; }
        [Column("fallback_set")]
        [StringLength(30)]
        public string FallbackSet { get; set; }
        [Column("prerun_script")]
        [StringLength(30)]
        public string PrerunScript { get; set; }
    }
}