// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Views
{
    [Keyless]
    public partial class DbForeignkeysCompatability
    {
        [Required]
        [Column("foreignkey_name")]
        [StringLength(128)]
        public string ForeignkeyName { get; set; }
    }
}