// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Views
{
    [Keyless]
    public partial class Dm0TrimmedEgmMetersSummary
    {
        [Column("egm_serial_number")]
        public int EgmSerialNumber { get; set; }
        [Column("summary_level")]
        public short SummaryLevel { get; set; }
        [Column("site_id")]
        public int? SiteId { get; set; }
        [Column("ssan")]
        public int Ssan { get; set; }
        [Column("denomination_id")]
        public short DenominationId { get; set; }
        [Column("stroke")]
        public int? Stroke { get; set; }
        [Column("turnover")]
        public int? Turnover { get; set; }
        [Column("wins")]
        public int? Wins { get; set; }
        [Column("cancelled_credits")]
        public int? CancelledCredits { get; set; }
        [Column("ticket_printer_out")]
        public int? TicketPrinterOut { get; set; }
        [Column("cents_in")]
        public int? CentsIn { get; set; }
        [Column("cents_out")]
        public int? CentsOut { get; set; }
        [Column("jackpot_wins")]
        public int? JackpotWins { get; set; }
        [Column("hopper_fills")]
        public int? HopperFills { get; set; }
        [Column("coins_in")]
        public int? CoinsIn { get; set; }
        [Column("coins_out")]
        public int? CoinsOut { get; set; }
        [Column("expected_coins_to_cashbox")]
        public int? ExpectedCoinsToCashbox { get; set; }
        [Column("cashless_credit_in")]
        public int? CashlessCreditIn { get; set; }
        [Column("cashless_credit_out")]
        public int? CashlessCreditOut { get; set; }
        [Column("expected_note_acceptor_amount")]
        public int? ExpectedNoteAcceptorAmount { get; set; }
        [Column("expected_notes_in_count")]
        public int? ExpectedNotesInCount { get; set; }
        [Column("total_res_cred_rem_turnover")]
        public int? TotalResCredRemTurnover { get; set; }
        [Column("total_res_cred_rem_wins")]
        public int? TotalResCredRemWins { get; set; }
        [Column("notes_in_number_5")]
        public int? NotesInNumber5 { get; set; }
        [Column("notes_in_number_10")]
        public int? NotesInNumber10 { get; set; }
        [Column("notes_in_number_20")]
        public int? NotesInNumber20 { get; set; }
        [Column("notes_in_number_50")]
        public int? NotesInNumber50 { get; set; }
        [Column("notes_in_number_100")]
        public int? NotesInNumber100 { get; set; }
    }
}