// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Views
{
    [Keyless]
    public partial class Gm0TrimmedEgmGameMetersSummary
    {
        [Column("op_days")]
        public int? OpDays { get; set; }
        [Column("egm_serial_number")]
        public int EgmSerialNumber { get; set; }
        [Column("game_number")]
        public short GameNumber { get; set; }
        [Column("start_datetime", TypeName = "datetime")]
        public DateTime StartDatetime { get; set; }
        [Column("game_variation_number")]
        public int GameVariationNumber { get; set; }
        [Column("site_id")]
        public short SiteId { get; set; }
        [Column("denomination_id")]
        public short DenominationId { get; set; }
        [Column("stroke")]
        public int? Stroke { get; set; }
        [Column("turnover")]
        public int? Turnover { get; set; }
        [Column("wins")]
        public int? Wins { get; set; }
        [Column("progressive_wins")]
        public int? ProgressiveWins { get; set; }
    }
}