// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Views
{
    [Keyless]
    public partial class Gm0TrimmedEgmMetersSummary
    {
        [Column("op_days")]
        public int? OpDays { get; set; }
        [Column("start_datetime", TypeName = "datetime")]
        public DateTime StartDatetime { get; set; }
        [Column("site_id")]
        public short SiteId { get; set; }
        [Column("egm_serial_number")]
        public int EgmSerialNumber { get; set; }
        [Column("denomination_id")]
        public short DenominationId { get; set; }
        [Column("ssan")]
        public int Ssan { get; set; }
        [Column("stroke")]
        public int? Stroke { get; set; }
        [Column("turnover")]
        public int? Turnover { get; set; }
        [Column("wins")]
        public int? Wins { get; set; }
        [Column("jackpot_wins")]
        public int? JackpotWins { get; set; }
    }
}