// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Views
{
    [Keyless]
    public partial class Jl0
    {
        [Column(TypeName = "smalldatetime")]
        public DateTime? ReportDate { get; set; }
        [Column("PoolID")]
        public int PoolId { get; set; }
        [StringLength(80)]
        public string Name { get; set; }
        public int Reset { get; set; }
        public int Maximum { get; set; }
        public int? Increment { get; set; }
        public int? ResetIncrement { get; set; }
        public double? OddsA { get; set; }
        public double? OddsB { get; set; }
        public bool? Regulatory { get; set; }
        public bool? Random { get; set; }
        public bool? Hidden { get; set; }
        public bool? Progressive { get; set; }
        [Column("EGMTriggered")]
        public bool? Egmtriggered { get; set; }
        public bool? WideArea { get; set; }
        public bool? EnabledStatus { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ConfigStartDateTime { get; set; }
    }
}