// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Views
{
    [Keyless]
    public partial class Jm0
    {
        [Column(TypeName = "smalldatetime")]
        public DateTime? ReportDate { get; set; }
        [Column("PoolID")]
        public int PoolId { get; set; }
        public int? ClosingAmount { get; set; }
        public int? Contributions { get; set; }
        public int? Hits { get; set; }
        public int? Wins { get; set; }
    }
}