// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Views
{
    [Keyless]
    public partial class Lm0JackpotMonthSimultaneousHits
    {
        [Column("pool_number")]
        public int? PoolNumber { get; set; }
        [Column("count_sim_hits")]
        public int? CountSimHits { get; set; }
        [Column("amount_sim_hits")]
        public int? AmountSimHits { get; set; }
    }
}