// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Views
{
    [Keyless]
    public partial class Lm0JackpotMonthSummary
    {
        [Column("site_id")]
        public short? SiteId { get; set; }
        [Column("pool_number")]
        public int PoolNumber { get; set; }
        [Column("main_cont")]
        public int? MainCont { get; set; }
        [Column("reset_cont")]
        public int? ResetCont { get; set; }
    }
}