// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Views
{
    [Keyless]
    public partial class Lo0
    {
        [Column(TypeName = "smalldatetime")]
        public DateTime? ReportDate { get; set; }
        [Column("MID")]
        public byte? Mid { get; set; }
        public int? Serial { get; set; }
        public int? Site { get; set; }
        [StringLength(4)]
        public string OwnerCode { get; set; }
        [Column(TypeName = "smalldatetime")]
        public DateTime? ConfigDate { get; set; }
    }
}