// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Views
{
    [Keyless]
    public partial class Mc0JackpotMonthHitsAmount
    {
        [Column("report_date", TypeName = "smalldatetime")]
        public DateTime? ReportDate { get; set; }
        [Column("pool_number")]
        public int? PoolNumber { get; set; }
        [Column("site_id")]
        public int? SiteId { get; set; }
        [Column("count_hits")]
        public int? CountHits { get; set; }
        [Column("amount_hits")]
        public int? AmountHits { get; set; }
    }
}