// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Views
{
    [Keyless]
    public partial class SiteLicence
    {
        [Column(TypeName = "smalldatetime")]
        public DateTime? ReportDate { get; set; }
        public int? Site { get; set; }
        public int LicenceNumber { get; set; }
    }
}