// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Views
{
    [Keyless]
    public partial class Vc0
    {
        [Column(TypeName = "smalldatetime")]
        public DateTime? ReportDate { get; set; }
        [Column("MID")]
        public byte? Mid { get; set; }
        public int? Serial { get; set; }
        [Column("GVN")]
        public int? Gvn { get; set; }
        public byte? Variation { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ConfigStartDateTime { get; set; }
    }
}