// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Views
{
    [Keyless]
    public partial class ViewAlhTurnoverPlayer
    {
        [Column("site_id")]
        public short? SiteId { get; set; }
        [Column("start_datetime", TypeName = "datetime")]
        public DateTime StartDatetime { get; set; }
        [Column("player_turnover", TypeName = "numeric(18, 4)")]
        public decimal? PlayerTurnover { get; set; }
        [Column("points_accrued", TypeName = "numeric(18, 4)")]
        public decimal? PointsAccrued { get; set; }
    }
}