// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Views
{
    [Keyless]
    public partial class ViewPatronMembershipDetails
    {
        [Column("creation_css_site_id")]
        public short CreationCssSiteId { get; set; }
        [Column("patron_id", TypeName = "numeric(18, 0)")]
        public decimal PatronId { get; set; }
        [Column("membership_id")]
        public int? MembershipId { get; set; }
        [Column("membership_type_id")]
        public int? MembershipTypeId { get; set; }
        [Column("account_id")]
        public int AccountId { get; set; }
        [Column("last_session_datetime", TypeName = "datetime")]
        public DateTime? LastSessionDatetime { get; set; }
        [Column("account_balance")]
        public int AccountBalance { get; set; }
        [Column("res_postal_code")]
        [StringLength(30)]
        public string ResPostalCode { get; set; }
        [Column("date_of_birth", TypeName = "datetime")]
        public DateTime? DateOfBirth { get; set; }
        [Column("patron_age_days")]
        public int? PatronAgeDays { get; set; }
        [Column("sex")]
        [StringLength(1)]
        public string Sex { get; set; }
        [Column("status")]
        [StringLength(10)]
        public string Status { get; set; }
        [Column("expiry_datetime", TypeName = "datetime")]
        public DateTime? ExpiryDatetime { get; set; }
    }
}