// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Views
{
    [Keyless]
    public partial class ViewAlhEgmaccruals
    {
        [Column("session_id")]
        [StringLength(8000)]
        public string SessionId { get; set; }
        [Required]
        [Column("session_type")]
        [StringLength(8)]
        public string SessionType { get; set; }
        [Column("card_id")]
        public int CardId { get; set; }
        [Required]
        [Column("game_name")]
        [StringLength(80)]
        public string GameName { get; set; }
        [Column("denomination")]
        public short Denomination { get; set; }
        [Column("stroke", TypeName = "numeric(18, 4)")]
        public decimal? Stroke { get; set; }
        [Column("turnover", TypeName = "numeric(18, 4)")]
        public decimal? Turnover { get; set; }
        [Column("wins", TypeName = "numeric(18, 4)")]
        public decimal? Wins { get; set; }
        [Column("jackpot_wins", TypeName = "numeric(18, 4)")]
        public decimal? JackpotWins { get; set; }
        [Column("start_datetime", TypeName = "datetime")]
        public DateTime? StartDatetime { get; set; }
        [Column("end_datetime", TypeName = "datetime")]
        public DateTime EndDatetime { get; set; }
        [Column("egm_location")]
        [StringLength(8000)]
        public string EgmLocation { get; set; }
        [Column("egm_accrual_points", TypeName = "numeric(18, 4)")]
        public decimal? EgmAccrualPoints { get; set; }
        [Column("membership_id")]
        public int? MembershipId { get; set; }
        [Column("cash_profit", TypeName = "numeric(18, 4)")]
        public decimal? CashProfit { get; set; }
        [Column("site_id")]
        public short? SiteId { get; set; }
    }
}