// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CougarDb.Models.Cougar.Views
{
    [Keyless]
    public partial class ViewAlhTransfers
    {
        [Column("session_id")]
        [StringLength(8000)]
        public string SessionId { get; set; }
        [Required]
        [Column("session_type")]
        [StringLength(8)]
        public string SessionType { get; set; }
        [Column("source_card_id")]
        public int SourceCardId { get; set; }
        [Column("source_membership_id")]
        public int? SourceMembershipId { get; set; }
        [Column("site_id")]
        public short? SiteId { get; set; }
        [Column("start_datetime", TypeName = "datetime")]
        public DateTime? StartDatetime { get; set; }
        [Column("destination_card_id")]
        [StringLength(50)]
        public string DestinationCardId { get; set; }
        [Column("destination_membership_id")]
        [StringLength(50)]
        public string DestinationMembershipId { get; set; }
        [Column("transfer_points", TypeName = "numeric(18, 4)")]
        public decimal? TransferPoints { get; set; }
        [Required]
        [Column("reason_code")]
        [StringLength(1)]
        public string ReasonCode { get; set; }
    }
}