// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CougarDb.Models.Cougar.StoredProcedures
{
    public partial class add_tito_lock_transactionResult
    {
        public DateTime? expires { get; set; }
        public string holder { get; set; }
    }
}
