// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CougarDb.Models.Cougar.StoredProcedures
{
    public partial class get_tag_configResult
    {
        public short site_id { get; set; }
        public short floor { get; set; }
        public short bank { get; set; }
        public short position { get; set; }
        public short? midm_card { get; set; }
        public short? midm_port { get; set; }
        public short? midm_address { get; set; }
        public int? egm_serial_number { get; set; }
        public short? manufacturer_id { get; set; }
        public int? activdata_id { get; set; }
        public string make { get; set; }
        public short token_id { get; set; }
        public int? token_base_currency_value { get; set; }
        public short denomination_id { get; set; }
        public short? denom_base_currency_value { get; set; }
        public short current_game { get; set; }
        public int? game_type_id { get; set; }
        public short? jackpot_levels { get; set; }
        public int current_variation_number { get; set; }
        public int? return_to_player { get; set; }
        public string external_number { get; set; }
    }
}
