// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CougarDb.Models.Cougar.StoredProcedures
{
    public partial class get_account_balancesResult
    {
        public byte tracking_type_id { get; set; }
        public decimal balance { get; set; }
        public decimal? available_balance { get; set; }
    }
}
