// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CougarDb.Models.Cougar.StoredProcedures
{
    public partial class get_device_configResult
    {
        public short site_id { get; set; }
        public int id { get; set; }
        public int? device_number { get; set; }
        public string device_type { get; set; }
        public string description { get; set; }
        public string location { get; set; }
        public short? midm_card { get; set; }
        public short? midm_port { get; set; }
        public short? midm_address { get; set; }
        public string spare_1 { get; set; }
        public string spare_2 { get; set; }
    }
}
