// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CougarDb.Models.Cougar.StoredProcedures
{
    public partial class get_floor_crt_available_payoutsResult
    {
        public decimal ticket_number { get; set; }
        public short? position { get; set; }
        public int egm_serial_number { get; set; }
        public DateTime transaction_datetime { get; set; }
        public string transaction_status { get; set; }
        public string transaction_type { get; set; }
        public int? cash_amount { get; set; }
        public int? amount { get; set; }
        public int is_assignable { get; set; }
        public string patron_name { get; set; }
    }
}
