// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CougarDb.Models.Cougar.StoredProcedures
{
    public partial class k_get_patron_statementResult
    {
        public DateTime logged_datetime { get; set; }
        public byte transaction_type_id { get; set; }
        public short css_site_id { get; set; }
        public decimal? amount { get; set; }
        public decimal? new_balance { get; set; }
        public string description { get; set; }
        public byte? system_id { get; set; }
        public int? transaction_id { get; set; }
    }
}
