// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CougarDb.Models.Cougar.StoredProcedures
{
    public partial class meters_txt_headerResult
    {
        public string h1 { get; set; }
        public string h2 { get; set; }
        public string h3 { get; set; }
        public string h4 { get; set; }
        public string h5 { get; set; }
        public int? h6 { get; set; }
    }
}
