// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CougarDb.Models.Cougar.StoredProcedures
{
    public partial class meters_txt_fileResult
    {
        public string SerialNo { get; set; }
        public string Stroke { get; set; }
        public string Turnover { get; set; }
        public string Wins { get; set; }
        public string CancelCr { get; set; }
        public string TicketOut { get; set; }
        public string CentsIn { get; set; }
        public string CentsOut { get; set; }
        public string SAPWins { get; set; }
        public string LPWins { get; set; }
        public string Reserved9 { get; set; }
        public string Reserved10 { get; set; }
        public string Reserved11 { get; set; }
        public string Reserved12 { get; set; }
        public string Reserved13 { get; set; }
        public string Reserved14 { get; set; }
        public string Reserved15 { get; set; }
        public string Refills { get; set; }
        public string TokensIn { get; set; }
        public string TokensOut { get; set; }
        public string CashBox { get; set; }
        public string CashIn { get; set; }
        public string CashOut { get; set; }
        [Column("Note$In")]
        public string NoteIn { get; set; }
        public string NotesIn { get; set; }
        public string Reserved24 { get; set; }
        public string Reserved25 { get; set; }
        public string Reserved26 { get; set; }
        public string Reserved27 { get; set; }
        public string Reserved28 { get; set; }
        public string Reserved29 { get; set; }
        public string Reserved30 { get; set; }
        public string Reserved31 { get; set; }
        public string SimplayIn { get; set; }
        public string JackpotIn { get; set; }
        public string SimplayOut { get; set; }
    }
}
