// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CougarDb.Models.Cougar.StoredProcedures
{
    public partial class rpt_WAJWinsResult
    {
        public string pool_name { get; set; }
        public DateTime event_datetime { get; set; }
        public string amount { get; set; }
        public string site { get; set; }
        public string description { get; set; }
    }
}
