// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CougarDb.Models.Cougar.StoredProcedures
{
    public partial class site_hourly_meters_summaryResult
    {
        public string Date { get; set; }
        public short Site_ID { get; set; }
        public string Time { get; set; }
        public int? Stroke { get; set; }
        public int? Turnover { get; set; }
        public int? Wins { get; set; }
        public int? LPWins { get; set; }
        public int? SAPWins { get; set; }
        public int? MeteredWin { get; set; }
    }
}
