// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CougarDb.Models.Cougar.StoredProcedures
{
    public partial class sp_mgw_weekly_analysis_reportResult
    {
        public string week { get; set; }
        public string Market { get; set; }
        [Column("avg daily turnover")]
        public decimal? avgdailyturnover { get; set; }
    }
}
