// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CougarDb.Models.Cougar.StoredProcedures
{
    public partial class tp_JackpotMetersVsChargesReconciliationResult
    {
        public string Date { get; set; }
        public short site_id { get; set; }
        public string premises { get; set; }
        public string item_name { get; set; }
        public int pool_number { get; set; }
        public string pool_name { get; set; }
        public decimal? jackpot_turnover { get; set; }
        public decimal? charged_turnover { get; set; }
        public decimal? diff_turnover { get; set; }
    }
}
