// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CougarDb.Models.Cougar.StoredProcedures
{
    public partial class tp_rptEGMsWeeklyPerformanceResult
    {
        public string premises { get; set; }
        public short? position { get; set; }
        public DateTime? week_starting { get; set; }
        public int? egm_serial_number { get; set; }
        public string description { get; set; }
        public decimal? sum_turnover { get; set; }
        public decimal? sum_revenue { get; set; }
    }
}
