// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CougarDb.Models.Cougar.StoredProcedures
{
    public partial class tp_rptJokersJackpotEGMsResult
    {
        public string Date { get; set; }
        [Column("#EGMs")]
        public int? EGMs { get; set; }
    }
}
