// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CougarDb.Models.Cougar.StoredProcedures
{
    public partial class update_column_patronResult
    {
        public string comment1 { get; set; }
        public string comment2 { get; set; }
        public string comment3 { get; set; }
    }
}
